# docker-compose -f docker-compose-dev.yml up -d

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    restart: always
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=${WEAVIATE_QUERY_DEFAULTS_LIMIT}
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=${WEAVIATE_ANONYMOUS_ACCESS_ENABLED}
      - PERSISTENCE_DATA_PATH=${WEAVIATE_PERSISTENCE_DATA_PATH}
      - ENABLE_MODULES=${WEAVIATE_ENABLE_MODULES}
      - DEFAULT_VECTORIZER_MODULE=${WEAVIATE_DEFAULT_VECTORIZER_MODULE}
      # TODO: provide weaviate OPENAI key `OPENAI_APIKEY` at runtime: https://weaviate.io/developers/weaviate/model-providers/openai/embeddings
      # - CLUSTER_HOSTNAME=${WEAVIATE_CLUSTER_HOSTNAME}
    volumes:
      - ./data/weaviate:/var/lib/weaviate

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./data/mongo:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  redis:
    # NOTE: this is for local dev with extra GUI component to check out Redis data on browser for debugging!
    #     Use redis/redis-stack-server in prod, more lightweight image without GUI!
    image: redis/redis-stack:latest  
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    # Reference the environment variable from the .env file
    # Docker Compose automatically loads .env and substitutes ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data

  prefect-server:
    image: prefecthq/prefect:3-latest
    entrypoint: ["prefect", "server", "start", "--host", "0.0.0.0"]  # Start Orion API 
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "4200:4200"
    volumes:
      - ./data/prefect_data:/home/python/.prefect  # persist flow run data
    depends_on:
      - postgres

# TODO:
# prefect-agent:
#   image: prefecthq/prefect:2-python3.10
#   depends_on:
#     - prefect-server
#   environment:
#     - PREFECT_API_URL=http://prefect-server:4200/api
#     - PREFECT_LOGGING_LEVEL=INFO
#   command: ["prefect", "agent", "start", "--work-queue", "default"]

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.app
  #   container_name: core_app
  #   restart: always
  #   ports:
  #     - "${APP_PORT}:${APP_PORT}"
  #   environment:
  #     - APP_ENV=${APP_ENV}
  #     - APP_PORT=${APP_PORT}
  #     # Pass through database and messaging URLs
  #     # - POSTGRES_USER=${POSTGRES_USER}
  #     # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     # - POSTGRES_DB=${POSTGRES_DB}
  #     - DATABASE_URL=${DATABASE_URL}
  #     - MONGO_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017
  #     - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
  #     - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
  #     # Set PYTHONPATH so that both the app root and services/ folder are in the path
  #     - PYTHONPATH=/app:/app/services
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - weaviate
  #     - mongo
  #     - postgres
  #     - rabbitmq
  #     - redis
  #     - prefect-server
