"""Add applied override tags field to workflow runs

Revision ID: 066f97d2f444
Revises: 0e798cefe0d9
Create Date: 2025-09-19 18:43:31.467146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '066f97d2f444'
down_revision: Union[str, None] = '0e798cefe0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kw_wf_workflow_run', sa.Column('applied_workflow_config_override_tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kw_wf_workflow_run', 'applied_workflow_config_override_tags')
    # ### end Alembic commands ###
