"""Add workflow name field for workflow runs

Revision ID: 0e56a8d3e6f5
Revises: 4a54cad110c5
Create Date: 2025-05-16 11:41:11.634114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e56a8d3e6f5'
down_revision: Union[str, None] = '4a54cad110c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kw_wf_workflow_run', sa.Column('workflow_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_kw_wf_workflow_run_workflow_name'), 'kw_wf_workflow_run', ['workflow_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kw_wf_workflow_run_workflow_name'), table_name='kw_wf_workflow_run')
    op.drop_column('kw_wf_workflow_run', 'workflow_name')
    # ### end Alembic commands ###
