"""Add retry_count field in workflowrun

Revision ID: 0e798cefe0d9
Revises: c168ebaaee1f
Create Date: 2025-08-30 16:00:52.261755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e798cefe0d9'
down_revision: Union[str, None] = 'c168ebaaee1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kw_wf_workflow_run', sa.Column('retry_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kw_wf_workflow_run', 'retry_count')
    # ### end Alembic commands ###
