"""Add 'node_is_tool' in NodeTemplate

Revision ID: 43d9c15416c9
Revises: 193e053ee14b
Create Date: 2025-05-21 10:36:44.265598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43d9c15416c9'
down_revision: Union[str, None] = '193e053ee14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kw_wf_node_template', sa.Column('node_is_tool', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_kw_wf_node_template_node_is_tool'), 'kw_wf_node_template', ['node_is_tool'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kw_wf_node_template_node_is_tool'), table_name='kw_wf_node_template')
    op.drop_column('kw_wf_node_template', 'node_is_tool')
    # ### end Alembic commands ###
