"""Add proper relationship cascade for user / org delete, add is_active to org

Revision ID: 5200095f9754
Revises: 6312c1a88ff2
Create Date: 2025-06-24 13:57:10.613638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5200095f9754'
down_revision: Union[str, None] = '6312c1a88ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiwiq_auth_org', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_kiwiq_auth_org_is_active'), 'kiwiq_auth_org', ['is_active'], unique=False)
    op.drop_constraint('kiwiq_auth_refresh_token_user_id_fkey', 'kiwiq_auth_refresh_token', type_='foreignkey')
    op.create_foreign_key(None, 'kiwiq_auth_refresh_token', 'kiwiq_auth_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('kiwiq_auth_user_org_role', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('kiwiq_auth_user_org_role_user_id_fkey', 'kiwiq_auth_user_org_role', type_='foreignkey')
    op.drop_constraint('kiwiq_auth_user_org_role_role_id_fkey', 'kiwiq_auth_user_org_role', type_='foreignkey')
    op.drop_constraint('kiwiq_auth_user_org_role_organization_id_fkey', 'kiwiq_auth_user_org_role', type_='foreignkey')
    op.create_foreign_key(None, 'kiwiq_auth_user_org_role', 'kiwiq_auth_role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'kiwiq_auth_user_org_role', 'kiwiq_auth_org', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'kiwiq_auth_user_org_role', 'kiwiq_auth_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kiwiq_billing_credit_purchase_user_id_fkey', 'kiwiq_billing_credit_purchase', type_='foreignkey')
    op.drop_constraint('kiwiq_billing_credit_purchase_org_id_fkey', 'kiwiq_billing_credit_purchase', type_='foreignkey')
    op.create_foreign_key(None, 'kiwiq_billing_credit_purchase', 'kiwiq_auth_org', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'kiwiq_billing_credit_purchase', 'kiwiq_auth_user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('kiwiq_billing_org_credits_org_id_fkey', 'kiwiq_billing_org_credits', type_='foreignkey')
    op.create_foreign_key(None, 'kiwiq_billing_org_credits', 'kiwiq_auth_org', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kiwiq_billing_org_net_credits_org_id_fkey', 'kiwiq_billing_org_net_credits', type_='foreignkey')
    op.create_foreign_key(None, 'kiwiq_billing_org_net_credits', 'kiwiq_auth_org', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kiwiq_billing_org_subscription_org_id_fkey', 'kiwiq_billing_org_subscription', type_='foreignkey')
    op.create_foreign_key(None, 'kiwiq_billing_org_subscription', 'kiwiq_auth_org', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kiwiq_billing_promotion_code_usage_org_id_fkey', 'kiwiq_billing_promotion_code_usage', type_='foreignkey')
    op.drop_constraint('kiwiq_billing_promotion_code_usage_user_id_fkey', 'kiwiq_billing_promotion_code_usage', type_='foreignkey')
    op.create_foreign_key(None, 'kiwiq_billing_promotion_code_usage', 'kiwiq_auth_user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'kiwiq_billing_promotion_code_usage', 'kiwiq_auth_org', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kiwiq_billing_usage_event_user_id_fkey', 'kiwiq_billing_usage_event', type_='foreignkey')
    op.drop_constraint('kiwiq_billing_usage_event_org_id_fkey', 'kiwiq_billing_usage_event', type_='foreignkey')
    op.create_foreign_key(None, 'kiwiq_billing_usage_event', 'kiwiq_auth_org', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'kiwiq_billing_usage_event', 'kiwiq_auth_user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('kiwiq_linkedin_oauth_user_id_fkey', 'kiwiq_linkedin_oauth', type_='foreignkey')
    op.create_foreign_key(None, 'kiwiq_linkedin_oauth', 'kiwiq_auth_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kw_wf_chat_thread_user_id_fkey', 'kw_wf_chat_thread', type_='foreignkey')
    op.create_foreign_key(None, 'kw_wf_chat_thread', 'kiwiq_auth_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kw_wf_hitl_job_org_id_fkey', 'kw_wf_hitl_job', type_='foreignkey')
    op.drop_constraint('kw_wf_hitl_job_requesting_run_id_fkey', 'kw_wf_hitl_job', type_='foreignkey')
    op.drop_constraint('kw_wf_hitl_job_assigned_user_id_fkey', 'kw_wf_hitl_job', type_='foreignkey')
    op.create_foreign_key(None, 'kw_wf_hitl_job', 'kw_wf_workflow_run', ['requesting_run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'kw_wf_hitl_job', 'kiwiq_auth_org', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'kw_wf_hitl_job', 'kiwiq_auth_user', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('kw_wf_prompt_template_owner_org_id_fkey', 'kw_wf_prompt_template', type_='foreignkey')
    op.create_foreign_key(None, 'kw_wf_prompt_template', 'kiwiq_auth_org', ['owner_org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kw_wf_schema_template_owner_org_id_fkey', 'kw_wf_schema_template', type_='foreignkey')
    op.create_foreign_key(None, 'kw_wf_schema_template', 'kiwiq_auth_org', ['owner_org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kw_wf_user_notification_user_id_fkey', 'kw_wf_user_notification', type_='foreignkey')
    op.drop_constraint('kw_wf_user_notification_related_run_id_fkey', 'kw_wf_user_notification', type_='foreignkey')
    op.drop_constraint('kw_wf_user_notification_org_id_fkey', 'kw_wf_user_notification', type_='foreignkey')
    op.create_foreign_key(None, 'kw_wf_user_notification', 'kiwiq_auth_org', ['org_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'kw_wf_user_notification', 'kw_wf_workflow_run', ['related_run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'kw_wf_user_notification', 'kiwiq_auth_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_kw_wf_workflow_created_by_user_id'), 'kw_wf_workflow', ['created_by_user_id'], unique=False)
    op.drop_constraint('kw_wf_workflow_owner_org_id_fkey', 'kw_wf_workflow', type_='foreignkey')
    op.drop_constraint('kw_wf_workflow_created_by_user_id_fkey', 'kw_wf_workflow', type_='foreignkey')
    op.create_foreign_key(None, 'kw_wf_workflow', 'kiwiq_auth_user', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'kw_wf_workflow', 'kiwiq_auth_org', ['owner_org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kw_wf_workflow_config_override_org_id_fkey', 'kw_wf_workflow_config_override', type_='foreignkey')
    op.drop_constraint('kw_wf_workflow_config_override_user_id_fkey', 'kw_wf_workflow_config_override', type_='foreignkey')
    op.create_foreign_key(None, 'kw_wf_workflow_config_override', 'kiwiq_auth_org', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'kw_wf_workflow_config_override', 'kiwiq_auth_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kw_wf_workflow_run_triggered_by_user_id_fkey', 'kw_wf_workflow_run', type_='foreignkey')
    op.drop_constraint('kw_wf_workflow_run_owner_org_id_fkey', 'kw_wf_workflow_run', type_='foreignkey')
    op.create_foreign_key(None, 'kw_wf_workflow_run', 'kiwiq_auth_user', ['triggered_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'kw_wf_workflow_run', 'kiwiq_auth_org', ['owner_org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kw_wf_workflow_run', type_='foreignkey')
    op.drop_constraint(None, 'kw_wf_workflow_run', type_='foreignkey')
    op.create_foreign_key('kw_wf_workflow_run_owner_org_id_fkey', 'kw_wf_workflow_run', 'kiwiq_auth_org', ['owner_org_id'], ['id'])
    op.create_foreign_key('kw_wf_workflow_run_triggered_by_user_id_fkey', 'kw_wf_workflow_run', 'kiwiq_auth_user', ['triggered_by_user_id'], ['id'])
    op.drop_constraint(None, 'kw_wf_workflow_config_override', type_='foreignkey')
    op.drop_constraint(None, 'kw_wf_workflow_config_override', type_='foreignkey')
    op.create_foreign_key('kw_wf_workflow_config_override_user_id_fkey', 'kw_wf_workflow_config_override', 'kiwiq_auth_user', ['user_id'], ['id'])
    op.create_foreign_key('kw_wf_workflow_config_override_org_id_fkey', 'kw_wf_workflow_config_override', 'kiwiq_auth_org', ['org_id'], ['id'])
    op.drop_constraint(None, 'kw_wf_workflow', type_='foreignkey')
    op.drop_constraint(None, 'kw_wf_workflow', type_='foreignkey')
    op.create_foreign_key('kw_wf_workflow_created_by_user_id_fkey', 'kw_wf_workflow', 'kiwiq_auth_user', ['created_by_user_id'], ['id'])
    op.create_foreign_key('kw_wf_workflow_owner_org_id_fkey', 'kw_wf_workflow', 'kiwiq_auth_org', ['owner_org_id'], ['id'])
    op.drop_index(op.f('ix_kw_wf_workflow_created_by_user_id'), table_name='kw_wf_workflow')
    op.drop_constraint(None, 'kw_wf_user_notification', type_='foreignkey')
    op.drop_constraint(None, 'kw_wf_user_notification', type_='foreignkey')
    op.drop_constraint(None, 'kw_wf_user_notification', type_='foreignkey')
    op.create_foreign_key('kw_wf_user_notification_org_id_fkey', 'kw_wf_user_notification', 'kiwiq_auth_org', ['org_id'], ['id'])
    op.create_foreign_key('kw_wf_user_notification_related_run_id_fkey', 'kw_wf_user_notification', 'kw_wf_workflow_run', ['related_run_id'], ['id'])
    op.create_foreign_key('kw_wf_user_notification_user_id_fkey', 'kw_wf_user_notification', 'kiwiq_auth_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'kw_wf_schema_template', type_='foreignkey')
    op.create_foreign_key('kw_wf_schema_template_owner_org_id_fkey', 'kw_wf_schema_template', 'kiwiq_auth_org', ['owner_org_id'], ['id'])
    op.drop_constraint(None, 'kw_wf_prompt_template', type_='foreignkey')
    op.create_foreign_key('kw_wf_prompt_template_owner_org_id_fkey', 'kw_wf_prompt_template', 'kiwiq_auth_org', ['owner_org_id'], ['id'])
    op.drop_constraint(None, 'kw_wf_hitl_job', type_='foreignkey')
    op.drop_constraint(None, 'kw_wf_hitl_job', type_='foreignkey')
    op.drop_constraint(None, 'kw_wf_hitl_job', type_='foreignkey')
    op.create_foreign_key('kw_wf_hitl_job_assigned_user_id_fkey', 'kw_wf_hitl_job', 'kiwiq_auth_user', ['assigned_user_id'], ['id'])
    op.create_foreign_key('kw_wf_hitl_job_requesting_run_id_fkey', 'kw_wf_hitl_job', 'kw_wf_workflow_run', ['requesting_run_id'], ['id'])
    op.create_foreign_key('kw_wf_hitl_job_org_id_fkey', 'kw_wf_hitl_job', 'kiwiq_auth_org', ['org_id'], ['id'])
    op.drop_constraint(None, 'kw_wf_chat_thread', type_='foreignkey')
    op.create_foreign_key('kw_wf_chat_thread_user_id_fkey', 'kw_wf_chat_thread', 'kiwiq_auth_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'kiwiq_linkedin_oauth', type_='foreignkey')
    op.create_foreign_key('kiwiq_linkedin_oauth_user_id_fkey', 'kiwiq_linkedin_oauth', 'kiwiq_auth_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'kiwiq_billing_usage_event', type_='foreignkey')
    op.drop_constraint(None, 'kiwiq_billing_usage_event', type_='foreignkey')
    op.create_foreign_key('kiwiq_billing_usage_event_org_id_fkey', 'kiwiq_billing_usage_event', 'kiwiq_auth_org', ['org_id'], ['id'])
    op.create_foreign_key('kiwiq_billing_usage_event_user_id_fkey', 'kiwiq_billing_usage_event', 'kiwiq_auth_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'kiwiq_billing_promotion_code_usage', type_='foreignkey')
    op.drop_constraint(None, 'kiwiq_billing_promotion_code_usage', type_='foreignkey')
    op.create_foreign_key('kiwiq_billing_promotion_code_usage_user_id_fkey', 'kiwiq_billing_promotion_code_usage', 'kiwiq_auth_user', ['user_id'], ['id'])
    op.create_foreign_key('kiwiq_billing_promotion_code_usage_org_id_fkey', 'kiwiq_billing_promotion_code_usage', 'kiwiq_auth_org', ['org_id'], ['id'])
    op.drop_constraint(None, 'kiwiq_billing_org_subscription', type_='foreignkey')
    op.create_foreign_key('kiwiq_billing_org_subscription_org_id_fkey', 'kiwiq_billing_org_subscription', 'kiwiq_auth_org', ['org_id'], ['id'])
    op.drop_constraint(None, 'kiwiq_billing_org_net_credits', type_='foreignkey')
    op.create_foreign_key('kiwiq_billing_org_net_credits_org_id_fkey', 'kiwiq_billing_org_net_credits', 'kiwiq_auth_org', ['org_id'], ['id'])
    op.drop_constraint(None, 'kiwiq_billing_org_credits', type_='foreignkey')
    op.create_foreign_key('kiwiq_billing_org_credits_org_id_fkey', 'kiwiq_billing_org_credits', 'kiwiq_auth_org', ['org_id'], ['id'])
    op.drop_constraint(None, 'kiwiq_billing_credit_purchase', type_='foreignkey')
    op.drop_constraint(None, 'kiwiq_billing_credit_purchase', type_='foreignkey')
    op.create_foreign_key('kiwiq_billing_credit_purchase_org_id_fkey', 'kiwiq_billing_credit_purchase', 'kiwiq_auth_org', ['org_id'], ['id'])
    op.create_foreign_key('kiwiq_billing_credit_purchase_user_id_fkey', 'kiwiq_billing_credit_purchase', 'kiwiq_auth_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'kiwiq_auth_user_org_role', type_='foreignkey')
    op.drop_constraint(None, 'kiwiq_auth_user_org_role', type_='foreignkey')
    op.drop_constraint(None, 'kiwiq_auth_user_org_role', type_='foreignkey')
    op.create_foreign_key('kiwiq_auth_user_org_role_organization_id_fkey', 'kiwiq_auth_user_org_role', 'kiwiq_auth_org', ['organization_id'], ['id'])
    op.create_foreign_key('kiwiq_auth_user_org_role_role_id_fkey', 'kiwiq_auth_user_org_role', 'kiwiq_auth_role', ['role_id'], ['id'])
    op.create_foreign_key('kiwiq_auth_user_org_role_user_id_fkey', 'kiwiq_auth_user_org_role', 'kiwiq_auth_user', ['user_id'], ['id'])
    op.alter_column('kiwiq_auth_user_org_role', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'kiwiq_auth_refresh_token', type_='foreignkey')
    op.create_foreign_key('kiwiq_auth_refresh_token_user_id_fkey', 'kiwiq_auth_refresh_token', 'kiwiq_auth_user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_kiwiq_auth_org_is_active'), table_name='kiwiq_auth_org')
    op.drop_column('kiwiq_auth_org', 'is_active')
    # ### end Alembic commands ###
