"""Make Billing model plan_id in subscription nullable

Revision ID: 5d8d78a57304
Revises: f8d1017911b3
Create Date: 2025-06-03 14:41:56.321959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d8d78a57304'
down_revision: Union[str, None] = 'f8d1017911b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kiwiq_billing_org_subscription', 'plan_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kiwiq_billing_org_subscription', 'plan_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
