"""Add LinkedIn integration models

Revision ID: 6312c1a88ff2
Revises: e99ca4d49594
Create Date: 2025-06-19 22:15:25.880573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6312c1a88ff2'
down_revision: Union[str, None] = 'e99ca4d49594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiwiq_linkedin_account',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('vanity_name', sa.String(length=255), nullable=True),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_linkedin_account_vanity_name'), 'kiwiq_linkedin_account', ['vanity_name'], unique=False)
    op.create_table('kiwiq_linkedin_integration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('linkedin_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('refresh_token_expires_in', sa.Integer(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('integration_state', sa.String(length=50), nullable=False),
    sa.Column('linkedin_orgs_roles', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['kiwiq_auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'linkedin_id', name='uq_user_linkedin_integration')
    )
    op.create_index(op.f('ix_kiwiq_linkedin_integration_id'), 'kiwiq_linkedin_integration', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_integration_integration_state'), 'kiwiq_linkedin_integration', ['integration_state'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_integration_linkedin_id'), 'kiwiq_linkedin_integration', ['linkedin_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_integration_user_id'), 'kiwiq_linkedin_integration', ['user_id'], unique=False)
    op.create_table('kiwiq_linkedin_org_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('linkedin_account_id', sa.String(length=255), nullable=False),
    sa.Column('linkedin_integration_id', sa.UUID(), nullable=False),
    sa.Column('managed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_in_linkedin_entity', sa.String(length=100), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linkedin_account_id'], ['kiwiq_linkedin_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linkedin_integration_id'], ['kiwiq_linkedin_integration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['managed_by_user_id'], ['kiwiq_auth_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['kiwiq_auth_org.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_account_id', 'organization_id', 'linkedin_integration_id', name='uq_org_linkedin_account')
    )
    op.create_index(op.f('ix_kiwiq_linkedin_org_account_id'), 'kiwiq_linkedin_org_account', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_org_account_is_active'), 'kiwiq_linkedin_org_account', ['is_active'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_org_account_is_shared'), 'kiwiq_linkedin_org_account', ['is_shared'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_org_account_linkedin_account_id'), 'kiwiq_linkedin_org_account', ['linkedin_account_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_org_account_linkedin_integration_id'), 'kiwiq_linkedin_org_account', ['linkedin_integration_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_org_account_managed_by_user_id'), 'kiwiq_linkedin_org_account', ['managed_by_user_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_org_account_organization_id'), 'kiwiq_linkedin_org_account', ['organization_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_org_account_status'), 'kiwiq_linkedin_org_account', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiwiq_linkedin_org_account_status'), table_name='kiwiq_linkedin_org_account')
    op.drop_index(op.f('ix_kiwiq_linkedin_org_account_organization_id'), table_name='kiwiq_linkedin_org_account')
    op.drop_index(op.f('ix_kiwiq_linkedin_org_account_managed_by_user_id'), table_name='kiwiq_linkedin_org_account')
    op.drop_index(op.f('ix_kiwiq_linkedin_org_account_linkedin_integration_id'), table_name='kiwiq_linkedin_org_account')
    op.drop_index(op.f('ix_kiwiq_linkedin_org_account_linkedin_account_id'), table_name='kiwiq_linkedin_org_account')
    op.drop_index(op.f('ix_kiwiq_linkedin_org_account_is_shared'), table_name='kiwiq_linkedin_org_account')
    op.drop_index(op.f('ix_kiwiq_linkedin_org_account_is_active'), table_name='kiwiq_linkedin_org_account')
    op.drop_index(op.f('ix_kiwiq_linkedin_org_account_id'), table_name='kiwiq_linkedin_org_account')
    op.drop_table('kiwiq_linkedin_org_account')
    op.drop_index(op.f('ix_kiwiq_linkedin_integration_user_id'), table_name='kiwiq_linkedin_integration')
    op.drop_index(op.f('ix_kiwiq_linkedin_integration_linkedin_id'), table_name='kiwiq_linkedin_integration')
    op.drop_index(op.f('ix_kiwiq_linkedin_integration_integration_state'), table_name='kiwiq_linkedin_integration')
    op.drop_index(op.f('ix_kiwiq_linkedin_integration_id'), table_name='kiwiq_linkedin_integration')
    op.drop_table('kiwiq_linkedin_integration')
    op.drop_index(op.f('ix_kiwiq_linkedin_account_vanity_name'), table_name='kiwiq_linkedin_account')
    op.drop_table('kiwiq_linkedin_account')
    # ### end Alembic commands ###
