"""Add workflow config override model and run tag field for annotating experiments

Revision ID: 72a4f76a4453
Revises: 0e56a8d3e6f5
Create Date: 2025-05-17 01:59:48.517363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72a4f76a4453'
down_revision: Union[str, None] = '0e56a8d3e6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kw_wf_workflow_config_override',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('workflow_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workflow_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('override_graph_schema', sa.JSON(), nullable=True),
    sa.Column('is_system_entity', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(is_system_entity = true AND user_id IS NULL AND org_id IS NULL) OR (is_system_entity = false AND (user_id IS NOT NULL OR org_id IS NOT NULL))', name='check_scope_constraint'),
    sa.CheckConstraint('(workflow_id IS NOT NULL AND workflow_name IS NULL) OR (workflow_id IS NULL AND workflow_name IS NOT NULL) OR (workflow_id IS NULL AND workflow_name IS NULL)', name='check_workflow_identifier'),
    sa.CheckConstraint('(workflow_id IS NULL) OR (workflow_version IS NULL)', name='check_workflow_version_constraint'),
    sa.ForeignKeyConstraint(['org_id'], ['kiwiq_auth_org.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kiwiq_auth_user.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['kw_wf_workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'workflow_name', 'workflow_version', 'is_system_entity', 'org_id', 'user_id', 'tag', name='uq_workflow_override_scope')
    )
    op.create_index(op.f('ix_kw_wf_workflow_config_override_id'), 'kw_wf_workflow_config_override', ['id'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_config_override_is_active'), 'kw_wf_workflow_config_override', ['is_active'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_config_override_is_system_entity'), 'kw_wf_workflow_config_override', ['is_system_entity'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_config_override_org_id'), 'kw_wf_workflow_config_override', ['org_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_config_override_tag'), 'kw_wf_workflow_config_override', ['tag'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_config_override_user_id'), 'kw_wf_workflow_config_override', ['user_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_config_override_workflow_id'), 'kw_wf_workflow_config_override', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_config_override_workflow_name'), 'kw_wf_workflow_config_override', ['workflow_name'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_config_override_workflow_version'), 'kw_wf_workflow_config_override', ['workflow_version'], unique=False)
    op.alter_column('kw_wf_user_notification', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('kw_wf_workflow_run', sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('kw_wf_workflow_run', sa.Column('applied_workflow_config_overrides', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('kw_wf_workflow_run', 'owner_org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_kw_wf_workflow_run_tag'), 'kw_wf_workflow_run', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kw_wf_workflow_run_tag'), table_name='kw_wf_workflow_run')
    op.alter_column('kw_wf_workflow_run', 'owner_org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('kw_wf_workflow_run', 'applied_workflow_config_overrides')
    op.drop_column('kw_wf_workflow_run', 'tag')
    op.alter_column('kw_wf_user_notification', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_kw_wf_workflow_config_override_workflow_version'), table_name='kw_wf_workflow_config_override')
    op.drop_index(op.f('ix_kw_wf_workflow_config_override_workflow_name'), table_name='kw_wf_workflow_config_override')
    op.drop_index(op.f('ix_kw_wf_workflow_config_override_workflow_id'), table_name='kw_wf_workflow_config_override')
    op.drop_index(op.f('ix_kw_wf_workflow_config_override_user_id'), table_name='kw_wf_workflow_config_override')
    op.drop_index(op.f('ix_kw_wf_workflow_config_override_tag'), table_name='kw_wf_workflow_config_override')
    op.drop_index(op.f('ix_kw_wf_workflow_config_override_org_id'), table_name='kw_wf_workflow_config_override')
    op.drop_index(op.f('ix_kw_wf_workflow_config_override_is_system_entity'), table_name='kw_wf_workflow_config_override')
    op.drop_index(op.f('ix_kw_wf_workflow_config_override_is_active'), table_name='kw_wf_workflow_config_override')
    op.drop_index(op.f('ix_kw_wf_workflow_config_override_id'), table_name='kw_wf_workflow_config_override')
    op.drop_table('kw_wf_workflow_config_override')
    # ### end Alembic commands ###
