"""change credits to float

Revision ID: 8ebd4fdd00d4
Revises: 5d8d78a57304
Create Date: 2025-06-03 16:58:35.377545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ebd4fdd00d4'
down_revision: Union[str, None] = '5d8d78a57304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiwiq_billing_credit_purchase', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.alter_column('kiwiq_billing_credit_purchase', 'credits_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.drop_column('kiwiq_billing_credit_purchase', 'amount_paid_cents')
    op.alter_column('kiwiq_billing_org_credits', 'credits_granted',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('kiwiq_billing_org_net_credits', 'credits_granted',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('kiwiq_billing_org_net_credits', 'credits_consumed',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('kiwiq_billing_promotion_code', 'credits_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('kiwiq_billing_promotion_code_usage', 'credits_applied',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.add_column('kiwiq_billing_subscription_plan', sa.Column('monthly_price', sa.Float(), nullable=True))
    op.add_column('kiwiq_billing_subscription_plan', sa.Column('annual_price', sa.Float(), nullable=True))
    op.drop_column('kiwiq_billing_subscription_plan', 'annual_price_cents')
    op.drop_column('kiwiq_billing_subscription_plan', 'monthly_price_cents')
    op.alter_column('kiwiq_billing_usage_event', 'credits_consumed',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kiwiq_billing_usage_event', 'credits_consumed',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.add_column('kiwiq_billing_subscription_plan', sa.Column('monthly_price_cents', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('kiwiq_billing_subscription_plan', sa.Column('annual_price_cents', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('kiwiq_billing_subscription_plan', 'annual_price')
    op.drop_column('kiwiq_billing_subscription_plan', 'monthly_price')
    op.alter_column('kiwiq_billing_promotion_code_usage', 'credits_applied',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('kiwiq_billing_promotion_code', 'credits_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('kiwiq_billing_org_net_credits', 'credits_consumed',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('kiwiq_billing_org_net_credits', 'credits_granted',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('kiwiq_billing_org_credits', 'credits_granted',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.add_column('kiwiq_billing_credit_purchase', sa.Column('amount_paid_cents', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('kiwiq_billing_credit_purchase', 'credits_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_column('kiwiq_billing_credit_purchase', 'amount_paid')
    # ### end Alembic commands ###
