"""Add is_public field to Workflow Model and add template/run permissions

Revision ID: 91aa2b63594c
Revises: 45ec2d5032ab
Create Date: 2025-04-10 23:52:29.952593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91aa2b63594c'
down_revision: Union[str, None] = '45ec2d5032ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kw_wf_workflow', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_kw_wf_workflow_is_public'), 'kw_wf_workflow', ['is_public'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kw_wf_workflow_is_public'), table_name='kw_wf_workflow')
    op.drop_column('kw_wf_workflow', 'is_public')
    # ### end Alembic commands ###
