"""Add tags in chat thread

Revision ID: a40c98140056
Revises: 43d9c15416c9
Create Date: 2025-05-23 20:29:01.546092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a40c98140056'
down_revision: Union[str, None] = '43d9c15416c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kw_wf_chat_thread', sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_kw_wf_chat_thread_tag'), 'kw_wf_chat_thread', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kw_wf_chat_thread_tag'), table_name='kw_wf_chat_thread')
    op.drop_column('kw_wf_chat_thread', 'tag')
    # ### end Alembic commands ###
