"""Add cascade delete to org/user roles when org or user is deleted and cascade delete for access tokens if user is deleted

Revision ID: aaa1a249529c
Revises: 91aa2b63594c
Create Date: 2025-04-11 12:44:57.358071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aaa1a249529c'
down_revision: Union[str, None] = '91aa2b63594c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
