"""Add input hash field to WorkflowRun model

Revision ID: c168ebaaee1f
Revises: 94b83df59d39
Create Date: 2025-08-15 00:46:21.750941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c168ebaaee1f'
down_revision: Union[str, None] = '94b83df59d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kw_wf_workflow_run', sa.Column('input_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_kw_wf_workflow_run_input_hash'), 'kw_wf_workflow_run', ['input_hash'], unique=False)
    op.create_index('kw_wf_workflow_run_input_hash_created_idx', 'kw_wf_workflow_run', ['workflow_id', 'input_hash', 'created_at'], unique=False)
    op.create_index('kw_wf_workflow_run_name_input_hash_created_idx', 'kw_wf_workflow_run', ['workflow_name', 'owner_org_id', 'input_hash', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('kw_wf_workflow_run_name_input_hash_created_idx', table_name='kw_wf_workflow_run')
    op.drop_index('kw_wf_workflow_run_input_hash_created_idx', table_name='kw_wf_workflow_run')
    op.drop_index(op.f('ix_kw_wf_workflow_run_input_hash'), table_name='kw_wf_workflow_run')
    op.drop_column('kw_wf_workflow_run', 'input_hash')
    # ### end Alembic commands ###
