"""Add LinkedIn Oauth model

Revision ID: e216af4589b9
Revises: a152f774891a
Create Date: 2025-06-18 21:30:51.124473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e216af4589b9'
down_revision: Union[str, None] = 'a152f774891a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiwiq_linkedin_oauth',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('oauth_state', sa.String(length=50), nullable=False),
    sa.Column('state_metadata', sa.JSON(), nullable=True),
    sa.Column('access_token', sa.String(length=1000), nullable=False),
    sa.Column('refresh_token', sa.String(length=1000), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('refresh_token_expires_in', sa.Integer(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['kiwiq_auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_linkedin_oauth_id'), 'kiwiq_linkedin_oauth', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_oauth_oauth_state'), 'kiwiq_linkedin_oauth', ['oauth_state'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_oauth_refresh_token_expires_at'), 'kiwiq_linkedin_oauth', ['refresh_token_expires_at'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_oauth_token_expires_at'), 'kiwiq_linkedin_oauth', ['token_expires_at'], unique=False)
    op.create_index(op.f('ix_kiwiq_linkedin_oauth_user_id'), 'kiwiq_linkedin_oauth', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiwiq_linkedin_oauth_user_id'), table_name='kiwiq_linkedin_oauth')
    op.drop_index(op.f('ix_kiwiq_linkedin_oauth_token_expires_at'), table_name='kiwiq_linkedin_oauth')
    op.drop_index(op.f('ix_kiwiq_linkedin_oauth_refresh_token_expires_at'), table_name='kiwiq_linkedin_oauth')
    op.drop_index(op.f('ix_kiwiq_linkedin_oauth_oauth_state'), table_name='kiwiq_linkedin_oauth')
    op.drop_index(op.f('ix_kiwiq_linkedin_oauth_id'), table_name='kiwiq_linkedin_oauth')
    op.drop_table('kiwiq_linkedin_oauth')
    # ### end Alembic commands ###
