"""Billing models

Revision ID: ef26bdf3908e
Revises: a40c98140056
Create Date: 2025-06-03 10:12:32.636910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef26bdf3908e'
down_revision: Union[str, None] = 'a40c98140056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiwiq_billing_promotion_code',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credit_type', sa.Enum('WORKFLOWS', 'WEB_SEARCHES', 'DOLLAR_CREDITS', name='kiwiq_billing_promo_credit_type_enum'), nullable=True),
    sa.Column('credits_amount', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('max_uses_per_org', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allowed_org_ids', sa.JSON(), nullable=True),
    sa.Column('granted_credits_expire_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_billing_promotion_code_code'), 'kiwiq_billing_promotion_code', ['code'], unique=True)
    op.create_index(op.f('ix_kiwiq_billing_promotion_code_credit_type'), 'kiwiq_billing_promotion_code', ['credit_type'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_promotion_code_expires_at'), 'kiwiq_billing_promotion_code', ['expires_at'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_promotion_code_id'), 'kiwiq_billing_promotion_code', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_promotion_code_is_active'), 'kiwiq_billing_promotion_code', ['is_active'], unique=False)
    op.create_table('kiwiq_billing_subscription_plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stripe_product_id', sa.String(), nullable=True),
    sa.Column('stripe_price_id_monthly', sa.String(), nullable=True),
    sa.Column('stripe_price_id_annual', sa.String(), nullable=True),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('monthly_credits', sa.JSON(), nullable=True),
    sa.Column('monthly_price_cents', sa.Integer(), nullable=False),
    sa.Column('annual_price_cents', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_trial_eligible', sa.Boolean(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_price_id_annual'),
    sa.UniqueConstraint('stripe_price_id_monthly')
    )
    op.create_index(op.f('ix_kiwiq_billing_subscription_plan_id'), 'kiwiq_billing_subscription_plan', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_subscription_plan_is_active'), 'kiwiq_billing_subscription_plan', ['is_active'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_subscription_plan_name'), 'kiwiq_billing_subscription_plan', ['name'], unique=True)
    op.create_index(op.f('ix_kiwiq_billing_subscription_plan_stripe_product_id'), 'kiwiq_billing_subscription_plan', ['stripe_product_id'], unique=True)
    op.create_table('kiwiq_billing_credit_purchase',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(), nullable=True),
    sa.Column('credit_type', sa.Enum('WORKFLOWS', 'WEB_SEARCHES', 'DOLLAR_CREDITS', name='kiwiq_billing_purchase_credit_type_enum'), nullable=True),
    sa.Column('credits_amount', sa.Integer(), nullable=False),
    sa.Column('amount_paid_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', 'REFUNDED', name='kiwiq_billing_payment_status_enum'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['kiwiq_auth_org.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kiwiq_auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_billing_credit_purchase_credit_type'), 'kiwiq_billing_credit_purchase', ['credit_type'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_credit_purchase_id'), 'kiwiq_billing_credit_purchase', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_credit_purchase_org_id'), 'kiwiq_billing_credit_purchase', ['org_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_credit_purchase_status'), 'kiwiq_billing_credit_purchase', ['status'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_credit_purchase_stripe_payment_intent_id'), 'kiwiq_billing_credit_purchase', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_kiwiq_billing_credit_purchase_user_id'), 'kiwiq_billing_credit_purchase', ['user_id'], unique=False)
    op.create_table('kiwiq_billing_org_credits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('credit_type', sa.Enum('WORKFLOWS', 'WEB_SEARCHES', 'DOLLAR_CREDITS', name='kiwiq_billing_credit_type_enum'), nullable=True),
    sa.Column('credits_granted', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('PROMOTION', 'SUBSCRIPTION', 'PURCHASE', name='kiwiq_billing_credit_source_type_enum'), nullable=True),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['kiwiq_auth_org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_billing_org_credits_credit_type'), 'kiwiq_billing_org_credits', ['credit_type'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_credits_expires_at'), 'kiwiq_billing_org_credits', ['expires_at'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_credits_id'), 'kiwiq_billing_org_credits', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_credits_is_expired'), 'kiwiq_billing_org_credits', ['is_expired'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_credits_org_id'), 'kiwiq_billing_org_credits', ['org_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_credits_source_type'), 'kiwiq_billing_org_credits', ['source_type'], unique=False)
    op.create_table('kiwiq_billing_org_net_credits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('credit_type', sa.Enum('WORKFLOWS', 'WEB_SEARCHES', 'DOLLAR_CREDITS', name='kiwiq_billing_credit_type_enum'), nullable=True),
    sa.Column('credits_granted', sa.Integer(), nullable=False),
    sa.Column('credits_consumed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['kiwiq_auth_org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kiwiq_billing_org_net_credits_org_credit_type', 'kiwiq_billing_org_net_credits', ['org_id', 'credit_type'], unique=True)
    op.create_index(op.f('ix_kiwiq_billing_org_net_credits_credit_type'), 'kiwiq_billing_org_net_credits', ['credit_type'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_net_credits_id'), 'kiwiq_billing_org_net_credits', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_net_credits_org_id'), 'kiwiq_billing_org_net_credits', ['org_id'], unique=False)
    op.create_table('kiwiq_billing_org_subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_item_id', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'PAUSED', name='kiwiq_billing_subscription_status_enum'), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seats_count', sa.Integer(), nullable=False),
    sa.Column('is_annual', sa.Boolean(), nullable=False),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('is_trial_active', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['kiwiq_auth_org.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['kiwiq_billing_subscription_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_billing_org_subscription_id'), 'kiwiq_billing_org_subscription', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_subscription_is_trial_active'), 'kiwiq_billing_org_subscription', ['is_trial_active'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_subscription_next_billing_date'), 'kiwiq_billing_org_subscription', ['next_billing_date'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_subscription_org_id'), 'kiwiq_billing_org_subscription', ['org_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_subscription_plan_id'), 'kiwiq_billing_org_subscription', ['plan_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_subscription_status'), 'kiwiq_billing_org_subscription', ['status'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_subscription_stripe_customer_id'), 'kiwiq_billing_org_subscription', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_org_subscription_stripe_subscription_id'), 'kiwiq_billing_org_subscription', ['stripe_subscription_id'], unique=True)
    op.create_table('kiwiq_billing_promotion_code_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('promo_code_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credits_applied', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['kiwiq_auth_org.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['kiwiq_billing_promotion_code.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kiwiq_auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_billing_promotion_code_usage_id'), 'kiwiq_billing_promotion_code_usage', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_promotion_code_usage_org_id'), 'kiwiq_billing_promotion_code_usage', ['org_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_promotion_code_usage_promo_code_id'), 'kiwiq_billing_promotion_code_usage', ['promo_code_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_promotion_code_usage_user_id'), 'kiwiq_billing_promotion_code_usage', ['user_id'], unique=False)
    op.create_table('kiwiq_billing_usage_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credit_type', sa.Enum('WORKFLOWS', 'WEB_SEARCHES', 'DOLLAR_CREDITS', name='kiwiq_billing_usage_credit_type_enum'), nullable=True),
    sa.Column('credits_consumed', sa.Integer(), nullable=False),
    sa.Column('usage_metadata', sa.JSON(), nullable=True),
    sa.Column('is_overage', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['kiwiq_auth_org.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kiwiq_auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_billing_usage_event_created_at'), 'kiwiq_billing_usage_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_usage_event_credit_type'), 'kiwiq_billing_usage_event', ['credit_type'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_usage_event_event_type'), 'kiwiq_billing_usage_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_usage_event_id'), 'kiwiq_billing_usage_event', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_usage_event_is_overage'), 'kiwiq_billing_usage_event', ['is_overage'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_usage_event_org_id'), 'kiwiq_billing_usage_event', ['org_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_usage_event_user_id'), 'kiwiq_billing_usage_event', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiwiq_billing_usage_event_user_id'), table_name='kiwiq_billing_usage_event')
    op.drop_index(op.f('ix_kiwiq_billing_usage_event_org_id'), table_name='kiwiq_billing_usage_event')
    op.drop_index(op.f('ix_kiwiq_billing_usage_event_is_overage'), table_name='kiwiq_billing_usage_event')
    op.drop_index(op.f('ix_kiwiq_billing_usage_event_id'), table_name='kiwiq_billing_usage_event')
    op.drop_index(op.f('ix_kiwiq_billing_usage_event_event_type'), table_name='kiwiq_billing_usage_event')
    op.drop_index(op.f('ix_kiwiq_billing_usage_event_credit_type'), table_name='kiwiq_billing_usage_event')
    op.drop_index(op.f('ix_kiwiq_billing_usage_event_created_at'), table_name='kiwiq_billing_usage_event')
    op.drop_table('kiwiq_billing_usage_event')
    op.drop_index(op.f('ix_kiwiq_billing_promotion_code_usage_user_id'), table_name='kiwiq_billing_promotion_code_usage')
    op.drop_index(op.f('ix_kiwiq_billing_promotion_code_usage_promo_code_id'), table_name='kiwiq_billing_promotion_code_usage')
    op.drop_index(op.f('ix_kiwiq_billing_promotion_code_usage_org_id'), table_name='kiwiq_billing_promotion_code_usage')
    op.drop_index(op.f('ix_kiwiq_billing_promotion_code_usage_id'), table_name='kiwiq_billing_promotion_code_usage')
    op.drop_table('kiwiq_billing_promotion_code_usage')
    op.drop_index(op.f('ix_kiwiq_billing_org_subscription_stripe_subscription_id'), table_name='kiwiq_billing_org_subscription')
    op.drop_index(op.f('ix_kiwiq_billing_org_subscription_stripe_customer_id'), table_name='kiwiq_billing_org_subscription')
    op.drop_index(op.f('ix_kiwiq_billing_org_subscription_status'), table_name='kiwiq_billing_org_subscription')
    op.drop_index(op.f('ix_kiwiq_billing_org_subscription_plan_id'), table_name='kiwiq_billing_org_subscription')
    op.drop_index(op.f('ix_kiwiq_billing_org_subscription_org_id'), table_name='kiwiq_billing_org_subscription')
    op.drop_index(op.f('ix_kiwiq_billing_org_subscription_next_billing_date'), table_name='kiwiq_billing_org_subscription')
    op.drop_index(op.f('ix_kiwiq_billing_org_subscription_is_trial_active'), table_name='kiwiq_billing_org_subscription')
    op.drop_index(op.f('ix_kiwiq_billing_org_subscription_id'), table_name='kiwiq_billing_org_subscription')
    op.drop_table('kiwiq_billing_org_subscription')
    op.drop_index(op.f('ix_kiwiq_billing_org_net_credits_org_id'), table_name='kiwiq_billing_org_net_credits')
    op.drop_index(op.f('ix_kiwiq_billing_org_net_credits_id'), table_name='kiwiq_billing_org_net_credits')
    op.drop_index(op.f('ix_kiwiq_billing_org_net_credits_credit_type'), table_name='kiwiq_billing_org_net_credits')
    op.drop_index('idx_kiwiq_billing_org_net_credits_org_credit_type', table_name='kiwiq_billing_org_net_credits')
    op.drop_table('kiwiq_billing_org_net_credits')
    op.drop_index(op.f('ix_kiwiq_billing_org_credits_source_type'), table_name='kiwiq_billing_org_credits')
    op.drop_index(op.f('ix_kiwiq_billing_org_credits_org_id'), table_name='kiwiq_billing_org_credits')
    op.drop_index(op.f('ix_kiwiq_billing_org_credits_is_expired'), table_name='kiwiq_billing_org_credits')
    op.drop_index(op.f('ix_kiwiq_billing_org_credits_id'), table_name='kiwiq_billing_org_credits')
    op.drop_index(op.f('ix_kiwiq_billing_org_credits_expires_at'), table_name='kiwiq_billing_org_credits')
    op.drop_index(op.f('ix_kiwiq_billing_org_credits_credit_type'), table_name='kiwiq_billing_org_credits')
    op.drop_table('kiwiq_billing_org_credits')
    op.drop_index(op.f('ix_kiwiq_billing_credit_purchase_user_id'), table_name='kiwiq_billing_credit_purchase')
    op.drop_index(op.f('ix_kiwiq_billing_credit_purchase_stripe_payment_intent_id'), table_name='kiwiq_billing_credit_purchase')
    op.drop_index(op.f('ix_kiwiq_billing_credit_purchase_status'), table_name='kiwiq_billing_credit_purchase')
    op.drop_index(op.f('ix_kiwiq_billing_credit_purchase_org_id'), table_name='kiwiq_billing_credit_purchase')
    op.drop_index(op.f('ix_kiwiq_billing_credit_purchase_id'), table_name='kiwiq_billing_credit_purchase')
    op.drop_index(op.f('ix_kiwiq_billing_credit_purchase_credit_type'), table_name='kiwiq_billing_credit_purchase')
    op.drop_table('kiwiq_billing_credit_purchase')
    op.drop_index(op.f('ix_kiwiq_billing_subscription_plan_stripe_product_id'), table_name='kiwiq_billing_subscription_plan')
    op.drop_index(op.f('ix_kiwiq_billing_subscription_plan_name'), table_name='kiwiq_billing_subscription_plan')
    op.drop_index(op.f('ix_kiwiq_billing_subscription_plan_is_active'), table_name='kiwiq_billing_subscription_plan')
    op.drop_index(op.f('ix_kiwiq_billing_subscription_plan_id'), table_name='kiwiq_billing_subscription_plan')
    op.drop_table('kiwiq_billing_subscription_plan')
    op.drop_index(op.f('ix_kiwiq_billing_promotion_code_is_active'), table_name='kiwiq_billing_promotion_code')
    op.drop_index(op.f('ix_kiwiq_billing_promotion_code_id'), table_name='kiwiq_billing_promotion_code')
    op.drop_index(op.f('ix_kiwiq_billing_promotion_code_expires_at'), table_name='kiwiq_billing_promotion_code')
    op.drop_index(op.f('ix_kiwiq_billing_promotion_code_credit_type'), table_name='kiwiq_billing_promotion_code')
    op.drop_index(op.f('ix_kiwiq_billing_promotion_code_code'), table_name='kiwiq_billing_promotion_code')
    op.drop_table('kiwiq_billing_promotion_code')
    # ### end Alembic commands ###
