"""Add template, workflow and User notifications/HITL models

Revision ID: f3cf1a4a6fc4
Revises: 3c171fa4f1eb
Create Date: 2025-04-08 23:55:19.686649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3cf1a4a6fc4'
down_revision: Union[str, None] = '3c171fa4f1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kw_wf_node_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('config_schema', sa.JSON(), nullable=True),
    sa.Column('launch_status', sa.Enum('EXPERIMENTAL', 'DEVELOPMENT', 'STAGING', 'PRODUCTION', name='kw_wf_node_launch_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='kw_wf_node_template_name_version_uc')
    )
    op.create_index(op.f('ix_kw_wf_node_template_id'), 'kw_wf_node_template', ['id'], unique=False)
    op.create_index(op.f('ix_kw_wf_node_template_launch_status'), 'kw_wf_node_template', ['launch_status'], unique=False)
    op.create_index(op.f('ix_kw_wf_node_template_name'), 'kw_wf_node_template', ['name'], unique=False)
    op.create_index(op.f('ix_kw_wf_node_template_version'), 'kw_wf_node_template', ['version'], unique=False)
    op.create_table('kw_wf_prompt_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_base_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_content', sa.Text(), nullable=True),
    sa.Column('input_variables', sa.JSON(), nullable=True),
    sa.Column('owner_org_id', sa.Uuid(), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_org_id'], ['kiwiq_auth_org.id'], ),
    sa.ForeignKeyConstraint(['parent_base_id'], ['kw_wf_prompt_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kw_wf_prompt_template_id'), 'kw_wf_prompt_template', ['id'], unique=False)
    op.create_index(op.f('ix_kw_wf_prompt_template_is_system_template'), 'kw_wf_prompt_template', ['is_system_template'], unique=False)
    op.create_index(op.f('ix_kw_wf_prompt_template_name'), 'kw_wf_prompt_template', ['name'], unique=False)
    op.create_index(op.f('ix_kw_wf_prompt_template_owner_org_id'), 'kw_wf_prompt_template', ['owner_org_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_prompt_template_parent_base_id'), 'kw_wf_prompt_template', ['parent_base_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_prompt_template_version'), 'kw_wf_prompt_template', ['version'], unique=False)
    op.create_index('kw_wf_prompt_template_org_name_version_idx', 'kw_wf_prompt_template', ['owner_org_id', 'name', 'version'], unique=True, postgresql_where=sa.text('NOT is_system_template'))
    op.create_index('kw_wf_prompt_template_system_name_version_idx', 'kw_wf_prompt_template', ['name', 'version'], unique=True, postgresql_where=sa.text('is_system_template'))
    op.create_table('kw_wf_schema_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_definition', sa.JSON(), nullable=True),
    sa.Column('schema_type', sa.Enum('JSON_SCHEMA', 'CONSTRUCT_DYNAMIC_SCHEMA', 'CODE_REGISTERED_SCHEMA', name='schematype'), nullable=False),
    sa.Column('owner_org_id', sa.Uuid(), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_org_id'], ['kiwiq_auth_org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kw_wf_schema_template_id'), 'kw_wf_schema_template', ['id'], unique=False)
    op.create_index(op.f('ix_kw_wf_schema_template_is_system_template'), 'kw_wf_schema_template', ['is_system_template'], unique=False)
    op.create_index(op.f('ix_kw_wf_schema_template_name'), 'kw_wf_schema_template', ['name'], unique=False)
    op.create_index(op.f('ix_kw_wf_schema_template_owner_org_id'), 'kw_wf_schema_template', ['owner_org_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_schema_template_schema_type'), 'kw_wf_schema_template', ['schema_type'], unique=False)
    op.create_index(op.f('ix_kw_wf_schema_template_version'), 'kw_wf_schema_template', ['version'], unique=False)
    op.create_index('kw_wf_schema_template_org_name_version_idx', 'kw_wf_schema_template', ['owner_org_id', 'name', 'version'], unique=True, postgresql_where=sa.text('NOT is_system_template'))
    op.create_index('kw_wf_schema_template_system_name_version_idx', 'kw_wf_schema_template', ['name', 'version'], unique=True, postgresql_where=sa.text('is_system_template'))
    op.create_table('kw_wf_workflow',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_base_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_org_id', sa.Uuid(), nullable=True),
    sa.Column('graph_config', sa.JSON(), nullable=True),
    sa.Column('version_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('launch_status', sa.Enum('EXPERIMENTAL', 'DEVELOPMENT', 'STAGING', 'PRODUCTION', name='kw_wf_workflow_launch_status_enum'), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['kiwiq_auth_user.id'], ),
    sa.ForeignKeyConstraint(['owner_org_id'], ['kiwiq_auth_org.id'], ),
    sa.ForeignKeyConstraint(['parent_base_id'], ['kw_wf_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kw_wf_workflow_id'), 'kw_wf_workflow', ['id'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_is_template'), 'kw_wf_workflow', ['is_template'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_launch_status'), 'kw_wf_workflow', ['launch_status'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_name'), 'kw_wf_workflow', ['name'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_owner_org_id'), 'kw_wf_workflow', ['owner_org_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_parent_base_id'), 'kw_wf_workflow', ['parent_base_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_version_tag'), 'kw_wf_workflow', ['version_tag'], unique=False)
    op.create_table('kw_wf_workflow_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('owner_org_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', 'WAITING_HITL', name='kw_wf_workflow_run_status_enum'), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detailed_results_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_org_id'], ['kiwiq_auth_org.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['kiwiq_auth_user.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['kw_wf_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kw_wf_workflow_run_id'), 'kw_wf_workflow_run', ['id'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_run_owner_org_id'), 'kw_wf_workflow_run', ['owner_org_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_run_status'), 'kw_wf_workflow_run', ['status'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_run_thread_id'), 'kw_wf_workflow_run', ['thread_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_run_triggered_by_user_id'), 'kw_wf_workflow_run', ['triggered_by_user_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_workflow_run_workflow_id'), 'kw_wf_workflow_run', ['workflow_id'], unique=False)
    op.create_table('kw_wf_hitl_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requesting_run_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_user_id', sa.Uuid(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESPONDED', 'EXPIRED', 'CANCELLED', name='kw_wf_hitl_job_status_enum'), nullable=False),
    sa.Column('request_details', sa.JSON(), nullable=True),
    sa.Column('response_schema', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['kiwiq_auth_user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['kiwiq_auth_org.id'], ),
    sa.ForeignKeyConstraint(['requesting_run_id'], ['kw_wf_workflow_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kw_wf_hitl_job_assigned_user_id'), 'kw_wf_hitl_job', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_hitl_job_id'), 'kw_wf_hitl_job', ['id'], unique=False)
    op.create_index(op.f('ix_kw_wf_hitl_job_org_id'), 'kw_wf_hitl_job', ['org_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_hitl_job_requesting_run_id'), 'kw_wf_hitl_job', ['requesting_run_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_hitl_job_status'), 'kw_wf_hitl_job', ['status'], unique=False)
    op.create_table('kw_wf_user_notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('related_run_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.Enum('RUN_COMPLETED', 'RUN_FAILED', 'HITL_REQUESTED', 'SYSTEM_MESSAGE', name='kw_wf_notification_type_enum'), nullable=False),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['kiwiq_auth_org.id'], ),
    sa.ForeignKeyConstraint(['related_run_id'], ['kw_wf_workflow_run.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kiwiq_auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kw_wf_user_notification_id'), 'kw_wf_user_notification', ['id'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_notification_is_read'), 'kw_wf_user_notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_notification_notification_type'), 'kw_wf_user_notification', ['notification_type'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_notification_org_id'), 'kw_wf_user_notification', ['org_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_notification_related_run_id'), 'kw_wf_user_notification', ['related_run_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_notification_user_id'), 'kw_wf_user_notification', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kw_wf_user_notification_user_id'), table_name='kw_wf_user_notification')
    op.drop_index(op.f('ix_kw_wf_user_notification_related_run_id'), table_name='kw_wf_user_notification')
    op.drop_index(op.f('ix_kw_wf_user_notification_org_id'), table_name='kw_wf_user_notification')
    op.drop_index(op.f('ix_kw_wf_user_notification_notification_type'), table_name='kw_wf_user_notification')
    op.drop_index(op.f('ix_kw_wf_user_notification_is_read'), table_name='kw_wf_user_notification')
    op.drop_index(op.f('ix_kw_wf_user_notification_id'), table_name='kw_wf_user_notification')
    op.drop_table('kw_wf_user_notification')
    op.drop_index(op.f('ix_kw_wf_hitl_job_status'), table_name='kw_wf_hitl_job')
    op.drop_index(op.f('ix_kw_wf_hitl_job_requesting_run_id'), table_name='kw_wf_hitl_job')
    op.drop_index(op.f('ix_kw_wf_hitl_job_org_id'), table_name='kw_wf_hitl_job')
    op.drop_index(op.f('ix_kw_wf_hitl_job_id'), table_name='kw_wf_hitl_job')
    op.drop_index(op.f('ix_kw_wf_hitl_job_assigned_user_id'), table_name='kw_wf_hitl_job')
    op.drop_table('kw_wf_hitl_job')
    op.drop_index(op.f('ix_kw_wf_workflow_run_workflow_id'), table_name='kw_wf_workflow_run')
    op.drop_index(op.f('ix_kw_wf_workflow_run_triggered_by_user_id'), table_name='kw_wf_workflow_run')
    op.drop_index(op.f('ix_kw_wf_workflow_run_thread_id'), table_name='kw_wf_workflow_run')
    op.drop_index(op.f('ix_kw_wf_workflow_run_status'), table_name='kw_wf_workflow_run')
    op.drop_index(op.f('ix_kw_wf_workflow_run_owner_org_id'), table_name='kw_wf_workflow_run')
    op.drop_index(op.f('ix_kw_wf_workflow_run_id'), table_name='kw_wf_workflow_run')
    op.drop_table('kw_wf_workflow_run')
    op.drop_index(op.f('ix_kw_wf_workflow_version_tag'), table_name='kw_wf_workflow')
    op.drop_index(op.f('ix_kw_wf_workflow_parent_base_id'), table_name='kw_wf_workflow')
    op.drop_index(op.f('ix_kw_wf_workflow_owner_org_id'), table_name='kw_wf_workflow')
    op.drop_index(op.f('ix_kw_wf_workflow_name'), table_name='kw_wf_workflow')
    op.drop_index(op.f('ix_kw_wf_workflow_launch_status'), table_name='kw_wf_workflow')
    op.drop_index(op.f('ix_kw_wf_workflow_is_template'), table_name='kw_wf_workflow')
    op.drop_index(op.f('ix_kw_wf_workflow_id'), table_name='kw_wf_workflow')
    op.drop_table('kw_wf_workflow')
    op.drop_index('kw_wf_schema_template_system_name_version_idx', table_name='kw_wf_schema_template', postgresql_where=sa.text('is_system_template'))
    op.drop_index('kw_wf_schema_template_org_name_version_idx', table_name='kw_wf_schema_template', postgresql_where=sa.text('NOT is_system_template'))
    op.drop_index(op.f('ix_kw_wf_schema_template_version'), table_name='kw_wf_schema_template')
    op.drop_index(op.f('ix_kw_wf_schema_template_schema_type'), table_name='kw_wf_schema_template')
    op.drop_index(op.f('ix_kw_wf_schema_template_owner_org_id'), table_name='kw_wf_schema_template')
    op.drop_index(op.f('ix_kw_wf_schema_template_name'), table_name='kw_wf_schema_template')
    op.drop_index(op.f('ix_kw_wf_schema_template_is_system_template'), table_name='kw_wf_schema_template')
    op.drop_index(op.f('ix_kw_wf_schema_template_id'), table_name='kw_wf_schema_template')
    op.drop_table('kw_wf_schema_template')
    op.drop_index('kw_wf_prompt_template_system_name_version_idx', table_name='kw_wf_prompt_template', postgresql_where=sa.text('is_system_template'))
    op.drop_index('kw_wf_prompt_template_org_name_version_idx', table_name='kw_wf_prompt_template', postgresql_where=sa.text('NOT is_system_template'))
    op.drop_index(op.f('ix_kw_wf_prompt_template_version'), table_name='kw_wf_prompt_template')
    op.drop_index(op.f('ix_kw_wf_prompt_template_parent_base_id'), table_name='kw_wf_prompt_template')
    op.drop_index(op.f('ix_kw_wf_prompt_template_owner_org_id'), table_name='kw_wf_prompt_template')
    op.drop_index(op.f('ix_kw_wf_prompt_template_name'), table_name='kw_wf_prompt_template')
    op.drop_index(op.f('ix_kw_wf_prompt_template_is_system_template'), table_name='kw_wf_prompt_template')
    op.drop_index(op.f('ix_kw_wf_prompt_template_id'), table_name='kw_wf_prompt_template')
    op.drop_table('kw_wf_prompt_template')
    op.drop_index(op.f('ix_kw_wf_node_template_version'), table_name='kw_wf_node_template')
    op.drop_index(op.f('ix_kw_wf_node_template_name'), table_name='kw_wf_node_template')
    op.drop_index(op.f('ix_kw_wf_node_template_launch_status'), table_name='kw_wf_node_template')
    op.drop_index(op.f('ix_kw_wf_node_template_id'), table_name='kw_wf_node_template')
    op.drop_table('kw_wf_node_template')
    # ### end Alembic commands ###
