"""add linkedin profiles count in subscription plans

Revision ID: f95f0460c737
Revises: 5200095f9754
Create Date: 2025-06-24 14:34:47.993039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f95f0460c737'
down_revision: Union[str, None] = '5200095f9754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiwiq_billing_subscription_plan', sa.Column('linkedin_profiles', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiwiq_billing_subscription_plan', 'linkedin_profiles')
    # ### end Alembic commands ###
