"""
# Inputs to workflow:
1. Generate content briefs for next X weeks: (X) int input optional, default 1
2. Load list of customer context docs such as dna, strategy doc, scraped posts etc
3. Load multiple user draft posts using multiple loader node within posts namespace, load latest N posts (limit and sort by updated_at, DESC); also load user preferences from onboarding namespace, user preferences doc which has user's requested posting frequency / week
5. Merge both lists and limit the merged list limit using merge aggregate node; also in another operation: compute next X weeks (input) multiplied by user preferences post frequency / week (this is number of content briefs we have to generate)
6. construct prompt for first generation (includes system prompt) with all user docs and merged list in prompt
7. Generate 1 structured output content brief; it reads message history from LLM; this also has fields such as date / time of posting; it sends structured outputs to all_generated_briefs with reducer collect values
8. check IF else on iteration limit, if we have generated the required number of briefs
9. Router node to route to store node to store all generated briefs OR to construct prompt for additional briefs
10. Construct prompt for additional briefs constructs user prompt which just says generate 1 more additional briefs, ensure difference from previous briefs; it sends to same above LLM node; the LLM node loads message history from central state where it can see previous briefs and generate the next brief
10. (after iteration loop ends) store node stores draft briefs in separate paths using filename pattern with draft ID
11. send all briefs to output node

"""

import asyncio
import logging
from typing import Dict, Any, Optional, List, Union, ClassVar, Type
import json
from enum import Enum

# Using Pydantic for easier schema generation
from pydantic import BaseModel, Field

# Internal dependencies (assuming similar structure to example)
from kiwi_client.test_run_workflow_client import (
    run_workflow_test,
    SetupDocInfo,
    CleanupDocInfo
)
from kiwi_client.schemas.workflow_constants import WorkflowRunStatus
from kiwi_client.workflows.document_models.customer_docs import (
    LINKEDIN_POST_DOCNAME_PATTERN,
    LINKEDIN_SCRAPING_NAMESPACE
#     # Define common namespaces/patterns if available, otherwise define here
#     USER_PROFILES_NAMESPACE, # Example
#     DRAFT_POSTS_NAMESPACE,   # Example
#     SCRAPED_POSTS_NAMESPACE, # Example
#     GENERATED_BRIEFS_NAMESPACE # Example
)

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# --- Workflow Configuration Constants ---

# Namespaces and Docnames (Adjust as per your actual storage structure)
USER_PREFERENCES_DOCNAME = "user_preferences_doc" # Example name for user preferences doc
GENERATED_BRIEFS_DOCNAME_PATTERN = "content_calendar_initial_brief_{item[brief_id]}"

# LLM Configuration
LLM_PROVIDER = "openai"
GENERATION_MODEL = "gpt-4.1" # Or gpt-4-turbo etc.
LLM_TEMPERATURE = 0.5
LLM_MAX_TOKENS = 2000 # Adjust as needed for brief generation

# Workflow Defaults
DEFAULT_WEEKS_TO_GENERATE = 1
# DEFAULT_DRAFTS_LIMIT = 20 # Default number of latest drafts to load
# DEFAULT_SCRAPED_LIMIT = 20 # Default number of scraped posts to load
PAST_CONTEXT_POSTS_LIMIT = 20 # Limit the combined list of posts fed to the LLM



# Namespaces (Define actual namespaces used in your storage)
USER_PROFILES_NAMESPACE = "user_profiles"
DRAFT_POSTS_NAMESPACE = "draft_posts"
SCRAPED_POSTS_NAMESPACE = "scraped_posts" # Namespace for scraped posts
GENERATED_BRIEFS_NAMESPACE = "generated_briefs"
STRATEGY_DOCS_NAMESPACE = "strategy_docs" # Namespace for strategy docs

# Document Names / Patterns
USER_DNA_DOCNAME = "user_dna_doc"
STRATEGY_DOCNAME = "q3_content_strategy"
# Store all briefs in a single versioned doc for easier cleanup/retrieval
GENERATED_BRIEFS_DOCNAME = "content_calendar_briefs"
GENERATED_BRIEFS_VERSION = "draft" # Version to store briefs under




# --- Pydantic Schemas for LLM Outputs ---

class ContentBriefSchema(BaseModel):
    """
    Defines the structure for a single content brief generated by the LLM.
    """
    brief_id: str = Field(..., description="Unique identifier for this brief (e.g., iteration number or UUID).")
    target_post_date: Optional[str] = Field(None, description="Suggested date for posting (e.g., 'YYYY-MM-DD'). Calculation might be complex and done post-generation or by LLM.")
    topic: str = Field(..., description="The core subject or theme for the LinkedIn post.")
    angle_or_hook: str = Field(..., description="A specific angle, perspective, or hook to make the post engaging.")
    key_talking_points: List[str] = Field(..., description="Bulleted list of essential points or messages to include.")
    call_to_action: Optional[str] = Field(None, description="A suggested call to action for the reader.")
    suggested_hashtags: List[str] = Field(default_factory=list, description="Relevant hashtags to potentially include.")
    # Optional: Link back to sources used? Requires passing post IDs to LLM.
    # relevant_source_ids: List[str] = Field(default_factory=list, description="IDs of source drafts/scraped posts used as inspiration.")


# --- Workflow Graph Schema Definition ---

workflow_graph_schema = {
  "nodes": {
    # --- 1. Input Node ---
    "input_node": {
      "node_id": "input_node",
      "node_name": "input_node",
      "node_config": {},
      "dynamic_output_schema": {
          "fields": {
              "weeks_to_generate": { "type": "int", "required": False, "default": DEFAULT_WEEKS_TO_GENERATE, "description": f"Number of weeks ahead to generate briefs for (default: {DEFAULT_WEEKS_TO_GENERATE})." },
              "customer_context_doc_configs": {
                  "type": "list",
                  "required": True,
                  "description": "List of document identifiers (namespace/docname pairs) for customer context like DNA, strategy docs."
              },
              "past_context_posts_limit": { "type": "int", "required": False, "default": PAST_CONTEXT_POSTS_LIMIT, "description": f"Max number of combined posts (drafts + scraped) to use for context (default: {PAST_CONTEXT_POSTS_LIMIT})."},
              "entity_name": {"type": "str", "required": True},
          }
        }
        # Outputs: user_id, weeks_to_generate, customer_context_doc_configs, draft_posts_limit, scraped_posts_limit, past_context_posts_limit -> $graph_state
    },

    # --- 2. Load Customer Context Documents and Scraped Posts (Single Node) ---
    "load_all_context_docs": {
        "node_id": "load_all_context_docs",
        "node_name": "load_customer_data",
        "node_config": {
            # Configure to load multiple documents based on the input list
            "load_configs_input_path": "customer_context_doc_configs", # Use the list from input node
            # Global defaults (can be overridden if needed per doc type via input structure)
            "global_is_shared": False,
            "global_is_system_entity": False,
            "global_version_config": {"version": "default"},
            "global_schema_options": {"load_schema": False},
        },
        
        # "dynamic_output_schema": { # Explicitly define expected output structure
        #     "fields": {
        #         # These keys MUST match the output_field_name in each config item
        #         "loaded_context_docs_list": {
        #             "type": "list", 
        #             "required": True,
        #             "description": "List containing the loaded content of each context document."
        #         },
        #         "loaded_scraped_posts": {
        #             "type": "list",
        #             "required": True,
        #             "description": "List of loaded scraped posts for the user."
        #         }
        #     }
        # }
        # Reads: context_and_scraped_configs (from input_node via edge mapping)
        # Writes: loaded_context_docs_list, loaded_scraped_posts -> $graph_state
    },

    # --- 3. Load Latest User Draft Posts ---
    "load_draft_posts": {
      "node_id": "load_draft_posts",
      "node_name": "load_multiple_customer_data", # Use the multi-loader node
      "node_config": {
          "namespace_filter": DRAFT_POSTS_NAMESPACE, # Filter by draft namespace
          "include_shared": False,        # User-specific drafts only
          "include_user_specific": True,
          "include_system_entities": False,
          # Pagination and Sorting (Inputs mapped from state)
          "skip": 0,
          "limit": PAST_CONTEXT_POSTS_LIMIT, # Mapped from draft_posts_limit input
          "sort_by": "updated_at",
          "sort_order": "desc",

          # Loading options (default)
          "global_version_config": None, # Load active version if versioned
          "global_schema_options": {"load_schema": False},

          # Output field name
          "output_field_name": "draft_posts" # The list will be under this key
      },
    #   "dynamic_output_schema": { # Define expected output
    #       "fields": {
    #           "draft_posts": { "type": "list", "required": True, "description": "List of loaded user draft posts." },
    #           "load_metadata": { "type": "dict", "required": True, "description": "Metadata about the loading operation."}
    #       }
    #   }
      # Reads: user_id (for filtering/permissions), draft_posts_limit (for config.limit) from state
      # Writes: draft_posts -> $graph_state
    },

    # --- 4. Merge Posts, Compute Limit, Prepare Generation Context ---
    "prepare_generation_context": {
      "node_id": "prepare_generation_context",
      "node_name": "merge_aggregate", # Use merge_aggregate to combine multiple sources
      "enable_node_fan_in": True, # Wait for all data loads before proceeding
      "node_config": {
        "operations": [
          # Operation 1: Merge Drafts and Scraped Posts and limit the result
          {
            "output_field_name": "final_merged_posts_for_prompt",
            # Order matters for priority (draft posts first, then scraped posts)
            "select_paths": ["draft_posts", "scraped_posts"], # Inputs from state
            "merge_strategy": {
                "map_phase": {"unspecified_keys_strategy": "ignore"}, # Only care about merging lists
                "reduce_phase": {
                    "default_reducer": "extend", # Combine the two lists
                    "error_strategy": "fail_node"
                },
                # Add transformation to limit the number of posts
                "post_merge_transformations": {
                    "final_merged_posts_for_prompt": {
                        "operation_type": "limit_list", 
                        "operand_path": "past_context_posts_limit" # Get limit value from input
                    }
                },
                "transformation_error_strategy": "skip_operation"
            },
            "merge_each_object_in_selected_list": False # Treat lists as atomic values to be EXTENDed
          },
          # Operation 2: Compute Total Briefs Needed - weeks_to_generate * posts_per_week
          {
            "output_field_name": "total_briefs_needed",
            "select_paths": ["user_preferences.posts_per_week"], # Inputs from state
             "merge_strategy": {
                #  "map_phase": {"unspecified_keys_strategy": "ignore"},
                #  "reduce_phase": {"default_reducer": ReducerType.REPLACE_RIGHT}, # Values overwrite
                 # Use transformation to calculate product of weeks and posts_per_week from user preferences
                 "post_merge_transformations": {
                      "total_briefs_needed": {
                          "operation_type": "multiply",
                          "operand_path": "weeks_to_generate" # Multiply posts_per_week by weeks_to_generate
                      }
                 },
                "transformation_error_strategy": "fail_node"
             },
             "merge_each_object_in_selected_list": False # Operate on values
          }
        ]
      },
      #  "dynamic_input_schema": { # Define inputs from state
      #     "fields": {
      #         "loaded_draft_posts": { "type": "list", "required": True },
      #         "loaded_scraped_posts": { "type": "list", "required": True },
      #         "loaded_context_docs_list": { "type": "dict", "required": True, "description": "Dict containing loaded context docs, including user preferences with posting frequency"},
      #         "weeks_to_generate": { "type": "int", "required": True },
      #         "past_context_posts_limit": { "type": "int", "required": True }
      #     }
      #  }
      # Reads: loaded_draft_posts, loaded_scraped_posts, loaded_context_docs_list, weeks_to_generate, past_context_posts_limit (from state)
      # Writes: merged_data containing final_merged_posts_for_prompt and total_briefs_needed -> $graph_state
    },

    # --- 9. Construct Brief Prompt (Inside Map Branch) ---
    "construct_brief_prompt": {
      "node_id": "construct_brief_prompt",
      "node_name": "prompt_constructor",
      "node_config": {
        "prompt_templates": {
          "brief_user_prompt": {
            "id": "brief_user_prompt",
            "template": """Generate content brief for a LinkedIn post.

            **Context:**
            - Content Strategy: {strategy_doc}
            - User Preferences: {user_preferences_json}
            - Customer Context Docs Summary/Highlights: {context_docs_summary}
            - Recent User Posts (Drafts/Scraped): {merged_posts_json}

            **Task:**
            Create a compelling content brief focusing on a specific topic relevant to the user's expertise and target audience, drawing inspiration from the provided context. Ensure the brief is actionable and aligns with the user's brand voice (implied from context). Define the topic, angle, key points, and optionally a CTA and hashtags.

            Respond ONLY with the JSON object matching the specified schema. Ensure 'brief_id' reflects the current iteration number.
            """,
            "variables": {
              "iteration_num": None,         # Mapped from iteration_info input
              "user_preferences_json": None, # Mapped from user_preferences
              "context_docs_summary": None,  # Mapped from strategy_doc and user_dna
              "merged_posts_json": None,     # Mapped from merged_posts
            },
            "construct_options": {
               "strategy_doc": "strategy_doc", # Map the number passed by the mapper
               "user_preferences_json": "user_preferences", # Map directly from user_preferences
               "context_docs_summary": "strategy_doc", # Map from strategy_doc
               "merged_posts_json": "merged_data.final_merged_posts_for_prompt", # Map directly from merged_posts
            }
          },
          "brief_system_prompt": {
            "id": "brief_system_prompt",
            "template": "You are an expert LinkedIn content strategist. Generate detailed and actionable content brief(s) based on the provided user context and Optional: previous briefs. Don't generate more than 1 brief at a time and ensure each brief is different from the previous ones. Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```",
            "variables": { "schema": json.dumps(ContentBriefSchema.model_json_schema(), indent=2) },
            "construct_options": {}
          }
        }
      }
      # Reads: merged_posts from prepare_generation_context, user_preferences/strategy_doc/user_dna from state
      # Writes: brief_user_prompt, brief_system_prompt for generate_brief node
    },

    # --- 10. Generate Brief (LLM - Inside Map Branch) ---
    "generate_brief": {
      "node_id": "generate_brief",
      "node_name": "llm",
      "node_config": {
          "llm_config": {
              "model_spec": {"provider": LLM_PROVIDER, "model": GENERATION_MODEL},
              "temperature": LLM_TEMPERATURE,
              "max_tokens": LLM_MAX_TOKENS
          },
          "output_schema": {
             "schema_definition": ContentBriefSchema.model_json_schema()
          },
      }
      # Reads (private): user_prompt, system_prompt
      # Reads (state): brief_generation_history (if manage_message_history=True)
      # Writes: structured_output -> all_generated_briefs (state reducer)
      # Writes: current_messages -> brief_generation_history (state reducer, if manage_message_history=True)
    },

    # --- Check Brief Count Node (after first brief generation) ---
    "check_brief_count": {
      "node_id": "check_brief_count",
      "node_name": "if_else_condition",
      "node_config": {
        "tagged_conditions": [
          {
            "tag": "brief_count_check", 
            "condition_groups": [{
              "logical_operator": "and",
              "conditions": [{
                "field": "metadata.iteration_count",
                "operator": "less_than",
                "value_path": "merged_data.total_briefs_needed"
              }]
            }],
            "group_logical_operator": "and"
          }
        ],
        "branch_logic_operator": "and"
      }
      # Reads: brief_generation_metadata from state, total_briefs_needed from state
      # Writes: branch, tag_results, condition_result
    },

    # --- Router Based on Brief Count Check ---
    "route_on_brief_count": {
      "node_id": "route_on_brief_count",
      "node_name": "router_node",
      "node_config": {
        "choices": ["construct_additional_brief_prompt", "store_all_briefs"],
        "allow_multiple": False,
        "choices_with_conditions": [
          {
            "choice_id": "construct_additional_brief_prompt", # Continue generating more briefs
            "input_path": "if_else_condition_tag_results::brief_count_check",
            "target_value": True
          },
          {
            "choice_id": "store_all_briefs", # End loop and store briefs
            "input_path": "if_else_condition_tag_results::brief_count_check",
            "target_value": False,
          }
        ]
      }
      # Reads: if_else_condition_tag_results, iteration_branch_result from check_brief_count
      # Routes to: construct_additional_brief_prompt OR store_all_briefs
    },

    # --- Construct Additional Brief Prompt ---
    "construct_additional_brief_prompt": {
      "node_id": "construct_additional_brief_prompt",
      "node_name": "prompt_constructor",
      "node_config": {
        "prompt_templates": {
          "additional_brief_prompt": {
            "id": "additional_brief_prompt",
            "template": "Generate one more content brief. Ensure it's different from your previous briefs.\n\nBe sure to follow the same schema and quality standards as your previous generations.",
            # "variables": {
            #   "prev_briefs_summary": None
            # },
            # "construct_options": {
            #   "prev_briefs_summary": "all_generated_briefs" # From state
            # }
          },
        }
      }
      # Reads: all_generated_briefs from state
      # Writes: additional_brief_prompt, system_prompt
    },


    # --- 11. Store All Generated Briefs (After Map Completes) ---
    "store_all_briefs": {
      "node_id": "store_all_briefs",
      "node_name": "store_customer_data", # Store the final list
      "node_config": {
          "global_versioning": { "is_versioned": True, "operation": "upsert_versioned", "version": "draft" },
          "global_is_shared": False,
          "store_configs": [
              {
                  # Store the entire list collected in the state
                  "input_field_path": "all_generated_briefs", # Mapped from state
                  "process_list_items_separately": True,
                  "target_path": {
                      "filename_config": {
                          "static_namespace": GENERATED_BRIEFS_NAMESPACE,
                           # Use user_id from state for the docname pattern
                          "docname_pattern": GENERATED_BRIEFS_DOCNAME_PATTERN # Example pattern
                      }
                  },
              }
          ],
      },
      "dynamic_input_schema": { # Define expected final inputs
          "fields": {
              # "all_generated_briefs": { "type": "list", "required": True, "description": "The complete list of generated content briefs." },
          }
      }
      # Reads: all_generated_briefs, user_id (from state)
      # Writes: paths_processed
    },

    # --- 12. Output Node ---
    "output_node": {
      "node_id": "output_node",
      "node_name": "output_node",
      "node_config": {},
      # "dynamic_input_schema": { # Define expected final inputs
      #     "fields": {
      #         "final_briefs_list": { "type": "list", "required": True, "description": "The complete list of generated content briefs." },
      #         "brief_paths_processed": { "type": "list", "required": False, "description": "Confirmation/path from the storage operation." }
      #     }
      # }
      # Reads: all_generated_briefs (mapped to final_briefs_list), paths_processed (mapped to save_confirmation)
    },

  },

  # --- Edges Defining Data Flow ---
  "edges": [
    # --- Input to State ---
    { "src_node_id": "input_node", "dst_node_id": "$graph_state", "mappings": [
        { "src_field": "weeks_to_generate", "dst_field": "weeks_to_generate" },
        { "src_field": "customer_context_doc_configs", "dst_field": "customer_context_doc_configs" },
        { "src_field": "past_context_posts_limit", "dst_field": "past_context_posts_limit" },
        { "src_field": "entity_name", "dst_field": "entity_name" },
      ]
    },
    
    

    { "src_node_id": "input_node", "dst_node_id": "load_all_context_docs", "mappings": [
        { "src_field": "customer_context_doc_configs", "dst_field": "customer_context_doc_configs" },
        { "src_field": "entity_name", "dst_field": "entity_name" },
      ], "description": "Trigger draft posts load."
    },

    { "src_node_id": "input_node", "dst_node_id": "load_draft_posts",
    },

    # --- State Updates from Loaders ---
    { "src_node_id": "load_all_context_docs", "dst_node_id": "$graph_state", "mappings": [
        # Store the lists under their respective keys in state
        { "src_field": "user_dna", "dst_field": "user_dna"},
        { "src_field": "user_preferences", "dst_field": "user_preferences"},
        { "src_field": "strategy_doc", "dst_field": "strategy_doc"},
        { "src_field": "scraped_posts", "dst_field": "scraped_posts"}
      ]
    },
    # --- Start Draft Posts Loading ---
    

    { "src_node_id": "load_draft_posts", "dst_node_id": "$graph_state", "mappings": [
        { "src_field": "draft_posts", "dst_field": "draft_posts"}
      ]
    },

    # --- Trigger Context Preparation after Loads ---
    # Edges from all loaders feeding into prepare_generation_context (fan-in enabled)





    # --- Trigger Context Preparation after Loads ---
    # Edges from all loaders feeding into prepare_generation_context (fan-in enabled)
    { "src_node_id": "load_all_context_docs", "dst_node_id": "prepare_generation_context"},
    { "src_node_id": "load_draft_posts", "dst_node_id": "prepare_generation_context"},

    # --- Mapping State to Context Prep Node ---
    { "src_node_id": "$graph_state", "dst_node_id": "prepare_generation_context", "mappings": [
        { "src_field": "draft_posts", "dst_field": "draft_posts" },
        { "src_field": "scraped_posts", "dst_field": "scraped_posts" },
        { "src_field": "past_context_posts_limit", "dst_field": "past_context_posts_limit" },
        { "src_field": "user_preferences", "dst_field": "user_preferences"},
        { "src_field": "weeks_to_generate", "dst_field": "weeks_to_generate" },
      ]
    },

    # --- State Update from Context Prep ---
    # { "src_node_id": "prepare_generation_context", "dst_node_id": "$graph_state", "mappings": [
    #     # Map relevant outputs to state
    #     { "src_field": "merged_data", "dst_field": "merged_posts" },
    #   ]
    # },



    # --- Map Iteration -> Construct Prompt (Private Edge) ---
    { "src_node_id": "prepare_generation_context", "dst_node_id": "construct_brief_prompt",
      "mappings": [
        { "src_field": "merged_data", "dst_field": "merged_data" },
      ]
    },

    { "src_node_id": "prepare_generation_context", "dst_node_id": "$graph_state",
      "mappings": [
        { "src_field": "merged_data", "dst_field": "merged_data" },
      ]
    },

    # --- State -> Construct Prompt (Public Edges for Context) ---
    { "src_node_id": "$graph_state", "dst_node_id": "construct_brief_prompt", "mappings": [
        { "src_field": "strategy_doc", "dst_field": "strategy_doc" },
        { "src_field": "user_dna", "dst_field": "user_dna"},
        { "src_field": "user_preferences", "dst_field": "user_preferences"},
      ]
    },

    # --- Construct Prompt -> Generate Brief (Private Edge) ---
    { "src_node_id": "construct_brief_prompt", "dst_node_id": "generate_brief", "mappings": [
        { "src_field": "brief_user_prompt", "dst_field": "user_prompt"},
        { "src_field": "brief_system_prompt", "dst_field": "system_prompt"}
      ], "description": "Private edge: Sends prompts to LLM."
    },
    # --- State -> Generate Brief (Public Edge for History) ---
    { "src_node_id": "$graph_state", "dst_node_id": "generate_brief", "mappings": [
        { "src_field": "brief_generation_history", "dst_field": "messages_history"}
      ]
    },

    # --- Generate Brief -> State (Public Edge for Collection/History Update) ---
    { "src_node_id": "generate_brief", "dst_node_id": "$graph_state", "mappings": [
        { "src_field": "structured_output", "dst_field": "all_generated_briefs"}, # Collected by reducer
        { "src_field": "current_messages", "dst_field": "brief_generation_history"} # Update history
      ]
    },
    

    # --- Generate Brief -> Check Brief Count
    { "src_node_id": "generate_brief", "dst_node_id": "check_brief_count", "mappings": [
        { "src_field": "metadata", "dst_field": "metadata"} # Collected by reducer
      ]},

    # --- State -> Check Brief Count (for metadata)
    { "src_node_id": "$graph_state", "dst_node_id": "check_brief_count", "mappings": [
        { "src_field": "merged_data", "dst_field": "merged_data" }
      ]
    },

    # --- Check Brief Count -> Route on Brief Count
    { "src_node_id": "check_brief_count", "dst_node_id": "route_on_brief_count", "mappings": [
        { "src_field": "tag_results", "dst_field": "if_else_condition_tag_results" },
        { "src_field": "condition_result", "dst_field": "if_else_overall_condition_result" }
      ]
    },

    # --- Route on Brief Count -> Construct Additional Brief Prompt (if more briefs needed)
    { "src_node_id": "route_on_brief_count", "dst_node_id": "construct_additional_brief_prompt" },

    # --- Route on Brief Count -> Store All Briefs (if all briefs generated)
    { "src_node_id": "route_on_brief_count", "dst_node_id": "store_all_briefs" },

     # --- Trigger Storage (After Map Completes) ---
    { "src_node_id": "$graph_state", "dst_node_id": "store_all_briefs", "mappings": [
        { "src_field": "all_generated_briefs", "dst_field": "all_generated_briefs"},
        { "src_field": "user_id", "dst_field": "user_id"} # For filename pattern
      ]
    },


    # # --- State -> Construct Additional Brief
    # { "src_node_id": "$graph_state", "dst_node_id": "construct_additional_brief_prompt", "mappings": [
    #     { "src_field": "all_generated_briefs", "dst_field": "all_generated_briefs" }
    #   ]
    # },

    # --- Construct Additional Brief -> Generate Brief (completes the loop)
    { "src_node_id": "construct_additional_brief_prompt", "dst_node_id": "generate_brief", "mappings": [
        { "src_field": "additional_brief_prompt", "dst_field": "user_prompt" },
      ]
    },

    { "src_node_id": "store_all_briefs", "dst_node_id": "output_node", 
     "mappings": [
        { "src_field": "paths_processed", "dst_field": "brief_paths_processed"}
      ]
     },

    # --- State -> Output ---
    { "src_node_id": "$graph_state", "dst_node_id": "output_node", "mappings": [
        { "src_field": "all_generated_briefs", "dst_field": "final_briefs_list"}
      ]
    },
  ],

  # --- Define Start and End ---
  "input_node_id": "input_node",
  "output_node_id": "output_node",

  # --- State Reducers ---
  "metadata": {
      "$graph_state": {
        "reducer": {
          "all_generated_briefs": "collect_values",   # Collect brief objects from each generation iteration
          # "brief_generation_history": "add_messages", # Or 'replace' if history isn't needed across iterations
          # "brief_generation_metadata": {
          #   "reducer_type": "replace", 
          #   "transform": {
          #     "iteration_count": {
          #       "expression": "value.get('iteration_count', 0) + 1"
          #     }
          #   }
          # }
        }
      }
  }
}


# --- Test Execution Logic (Placeholder) ---

async def main_test_content_calendar_workflow():
    """
    Placeholder for testing the Content Calendar Entry Workflow.
    Requires defining setup docs, expected outputs, etc.
    """
    test_name = "Content Calendar Entry Workflow Test"
    print(f"--- Starting {test_name} --- ")

    # Example Inputs (Adjust USER_ID and context doc list)
    test_user_id = "test-user-123"
    test_context_docs = [
        {
            "filename_config": {
                "static_namespace": USER_PROFILES_NAMESPACE, 
                "static_docname": USER_DNA_DOCNAME,
            },
            "output_field_name": "user_dna"  # Field where the loaded DNA doc will be stored
        },
        {
            "filename_config": {
                "static_namespace": USER_PROFILES_NAMESPACE, 
                "static_docname": USER_PREFERENCES_DOCNAME,
            },
            "output_field_name": "user_preferences"  # Field for user preferences
        },
        {
            "filename_config": {
                "static_namespace": STRATEGY_DOCS_NAMESPACE, 
                "static_docname": STRATEGY_DOCNAME,
                
            },
            "output_field_name": "strategy_doc"  # Field for strategy document
        },
        {
            "filename_config": {
                "static_namespace": LINKEDIN_SCRAPING_NAMESPACE,
                # Use entity_name from node input (mapped from input_node)
                "input_docname_field": "entity_name", # Field in *this node's* input
                "input_docname_field_pattern": LINKEDIN_POST_DOCNAME_PATTERN # "posts_{item}"
            },
            "output_field_name": "scraped_posts" # Expect output: {"raw_posts_data": [{"urn": "...", "text": "..."}, ...]}
        },
    ]
    # Define test inputs with realistic values
    test_inputs = {
        "entity_name": f"Talal Syed",  # For LinkedIn scraping pattern
        "weeks_to_generate": 1,  # Generate for 2 weeks
        "customer_context_doc_configs": test_context_docs,
        "past_context_posts_limit": 75  # Combined limit for context
    }

    # --- Define Setup & Cleanup Docs ---
    # Setup: Create user_preferences_doc, context docs, mock draft posts, mock scraped posts
    # Cleanup: Remove generated calendar doc and temporary setup docs

    # Create realistic test data for setup
    setup_docs: List[SetupDocInfo] = [
        {
            'namespace': USER_PROFILES_NAMESPACE, 
            'docname': USER_PREFERENCES_DOCNAME,
            'initial_data': {
                "posts_per_week": 3,  # User wants 3 posts per week
                "preferred_posting_days": ["Monday", "Wednesday", "Friday"],
                "preferred_topics": ["Leadership", "Industry Trends", "Professional Development"],
                "content_tone": "Professional with personal insights"
            }, 
            'is_versioned': False, 
            'is_shared': False
        },
        {
            'namespace': USER_PROFILES_NAMESPACE, 
            'docname': USER_DNA_DOCNAME,
            'initial_data': {
                "professional_background": "Marketing executive with 15+ years experience in tech",
                "expertise_areas": ["Digital Marketing", "Brand Strategy", "Team Leadership"],
                "target_audience": "Marketing professionals and business leaders",
                "content_goals": "Establish thought leadership and drive engagement",
                "personal_style": "Conversational but authoritative"
            }, 
            'is_versioned': False, 
            'is_shared': False
        },
        {
            'namespace': STRATEGY_DOCS_NAMESPACE, 
            'docname': STRATEGY_DOCNAME,
            'initial_data': {
                "quarterly_focus": "Building personal brand through consistent engagement",
                "key_themes": ["Innovation in marketing", "Leadership challenges", "Industry disruption"],
                "content_pillars": ["Educational", "Inspirational", "Conversational"],
                "success_metrics": ["Engagement rate", "Profile views", "Connection growth"]
            }, 
            'is_versioned': False, 
            'is_shared': False
        },
        # Mock draft posts
        {
            'namespace': DRAFT_POSTS_NAMESPACE, 
            'docname': f"draft_post_1_{test_user_id}",
            'initial_data': {
                "title": "Thoughts on AI in Marketing",
                "content": "AI is transforming how we approach marketing campaigns...",
                "created_at": "2023-06-01T10:00:00Z",
                "updated_at": "2023-06-02T14:30:00Z",
                "status": "draft"
            }, 
            'is_versioned': False, 
            'is_shared': False
        },
        {
            'namespace': DRAFT_POSTS_NAMESPACE, 
            'docname': f"draft_post_2_{test_user_id}",
            'initial_data': {
                "title": "Leadership Lessons from 2023",
                "content": "This year has taught me valuable lessons about remote leadership...",
                "created_at": "2023-06-05T09:15:00Z",
                "updated_at": "2023-06-05T16:45:00Z",
                "status": "draft"
            }, 
            'is_versioned': False, 
            'is_shared': False
        },
    ]

    # Define cleanup docs to remove test artifacts after test completion
    output_docname_pattern = "content_calendar_{item}_latest"
    output_docname = output_docname_pattern.format(item=test_user_id)
    cleanup_docs: List[CleanupDocInfo] = [
        # Clean up the generated briefs document
        {'namespace': GENERATED_BRIEFS_NAMESPACE, 'docname': output_docname, 'is_versioned': False, 'is_shared': False},
        # Clean up all setup docs
        {'namespace': USER_PROFILES_NAMESPACE, 'docname': USER_PREFERENCES_DOCNAME, 'is_versioned': False, 'is_shared': False},
        {'namespace': USER_PROFILES_NAMESPACE, 'docname': USER_DNA_DOCNAME, 'is_versioned': False, 'is_shared': False},
        {'namespace': STRATEGY_DOCS_NAMESPACE, 'docname': STRATEGY_DOCNAME, 'is_versioned': False, 'is_shared': False},
        {'namespace': DRAFT_POSTS_NAMESPACE, 'docname': f"draft_post_1_{test_user_id}", 'is_versioned': True, 'is_shared': False},
        {'namespace': DRAFT_POSTS_NAMESPACE, 'docname': f"draft_post_2_{test_user_id}", 'is_versioned': True, 'is_shared': False},
    ]

    print("--- Setup/Cleanup Definitions (Complete) ---")
    print(f"Output Calendar Doc: {GENERATED_BRIEFS_NAMESPACE}/{output_docname}")
    print(f"Setup Docs: {len(setup_docs)} documents prepared")
    print(f"Cleanup Docs: {len(cleanup_docs)} documents to be removed after test")
    print("------------------------------------------------")

    # --- Define Custom Output Validation ---
    async def validate_calendar_output(outputs: Optional[Dict[str, Any]]) -> bool:
        assert outputs is not None, "Validation Failed: Workflow returned no outputs."
        logger.info("Validating content calendar workflow outputs...")
        assert 'final_briefs_list' in outputs, "Validation Failed: 'final_briefs_list' missing."
        assert isinstance(outputs['final_briefs_list'], list), "Validation Failed: 'final_briefs_list' is not a list."
        
        # Calculate expected number of briefs based on user preferences
        user_prefs = next((doc['initial_data'] for doc in setup_docs 
                          if doc['namespace'] == USER_PROFILES_NAMESPACE and doc['docname'] == USER_PREFERENCES_DOCNAME), None)
        posts_per_week = user_prefs.get('posts_per_week', 3) if user_prefs else 3
        expected_count = test_inputs.get("weeks_to_generate", DEFAULT_WEEKS_TO_GENERATE) * posts_per_week
        
        # Validate brief count
        actual_count = len(outputs.get('final_briefs_list', []))
        assert actual_count == expected_count, f"Validation Failed: Expected {expected_count} briefs, found {actual_count}."
        
        # Validate brief structure
        for brief in outputs.get('final_briefs_list', []):
            assert 'brief_id' in brief, "Brief missing required field: brief_id"
            assert 'topic' in brief, "Brief missing required field: topic"
            assert 'angle_or_hook' in brief, "Brief missing required field: angle_or_hook"
            assert 'key_talking_points' in brief, "Brief missing required field: key_talking_points"
            assert isinstance(brief.get('key_talking_points', []), list), "key_talking_points must be a list"
        
        logger.info(f"   Found {actual_count} briefs, expected {expected_count}.")
        logger.info("✓ Output structure validation passed.")
        return True

    # --- Execute Test (Uncomment when ready to run) ---
    print("\n--- Running Workflow Test ---")
    final_run_status_obj, final_run_outputs = await run_workflow_test(
        test_name=test_name,
        workflow_graph_schema=workflow_graph_schema,
        initial_inputs=test_inputs,
        expected_final_status=WorkflowRunStatus.COMPLETED,
        setup_docs=setup_docs,
        cleanup_docs=cleanup_docs,
        validate_output_func=validate_calendar_output,
        stream_intermediate_results=True,
        poll_interval_sec=5,
        timeout_sec=1800 # Allow time for multiple LLM calls
    )

    print(f"--- {test_name} Finished (Placeholder Execution) --- ")
    # if 'final_run_status_obj' in locals(): # Check if run_workflow_test was actually called
    #     print(f"Final Status: {final_run_status_obj.status}")
    #     if final_run_outputs:
    #         print(f"Final Outputs: {final_run_outputs}")
    #     if final_run_status_obj.status != WorkflowRunStatus.COMPLETED:
    #         print(f"Error Message: {final_run_status_obj.error_message}")


if __name__ == "__main__":
    print("="*50)
    print("Content Calendar Entry Workflow Definition")
    print("="*50)
    # Basic logging for validation function if run standalone
    logging.basicConfig(level=logging.INFO)

    # Placeholder for running the async test function
    # Ensure event loop is managed correctly if running this script directly
    # Example using asyncio.run:
    try:
        asyncio.run(main_test_content_calendar_workflow())
    except KeyboardInterrupt:
        print("\nExecution interrupted.")
    # except Exception as e:
    #     print(f"\nError running test: {e}")
    #     logger.exception("Test execution failed")

    # print("\nSchema definition and test logic placeholder complete.")
    # print(f"PYTHONPATH=. python {__file__}") # Assuming run from project root

