"""

Flow: 
1. input node -> load_all_context_docs and load_draft_posts
2. [load_all_context_docs, load_draft_posts] -> construct_initial_concepts_prompt (enable_node_fan_in true)
3. construct_initial_concepts_prompt -> generate_concepts
4. generate_concepts -> store_concepts
5. store_concepts -> capture_user_choice
5. capture_user_choice -> route_on_user_choice
6. route_on_user_choice -> construct_concepts_regeneration_prompt [selection: regenerate concepts]
7. route_on_user_choice -> output_node [selection: Go back to initial ideas brief generation]
8. route_on_user_choice -> filter_selected_concepts [selection: select list of concepts]
9. construct_concepts_regeneration_prompt -> generate_concepts (concepts regeneration loop, generate_concepts reads message_history from state)
10. filter_selected_concepts -> construct_update_content_brief_prompt
11. construct_update_content_brief_prompt -> generated_updated_content_brief
12. generated_updated_content_brief -> save_updated_content_brief
13. save_updated_content_brief -> output_node
"""

import asyncio
import logging
from typing import Dict, Any, Optional, List, Union, ClassVar, Type
import json
from enum import Enum

# Using Pydantic for easier schema generation
from pydantic import BaseModel, Field

# Internal dependencies
from kiwi_client.test_run_workflow_client import (
    run_workflow_test,
    SetupDocInfo,
    CleanupDocInfo
)
from kiwi_client.schemas.workflow_constants import WorkflowRunStatus

from kiwi_client.workflows.document_models.customer_docs import (
    # User DNA
    USER_DNA_DOCNAME,
    USER_DNA_NAMESPACE_TEMPLATE,
    USER_DNA_IS_VERSIONED,
    # LinkedIn scraping
    LINKEDIN_SCRAPING_NAMESPACE_TEMPLATE,
    LINKEDIN_POST_DOCNAME,
    # Content Drafts
    CONTENT_DRAFT_DOCNAME,
    CONTENT_DRAFT_NAMESPACE_TEMPLATE,
    CONTENT_DRAFT_IS_VERSIONED,
    # Content Brief
    CONTENT_BRIEF_DOCNAME,
    CONTENT_BRIEF_NAMESPACE_TEMPLATE,
    CONTENT_BRIEF_IS_VERSIONED,
    CONTENT_BRIEF_DEFAULT_VERSION,
    CONTENT_BRIEF_FINAL_VERSION,
    # Content Concept
    CONCEPT_DOCNAME,
    CONCEPT_NAMESPACE_TEMPLATE,
    CONCEPT_IS_VERSIONED
)

from kiwi_client.workflows.llm_inputs.content_calendar_brief import BRIEF_LLM_OUTPUT_SCHEMA

from kiwi_client.workflows.llm_inputs.initial_brief_to_concept_to_final_brief import (
    INITIAL_CONCEPTS_USER_PROMPT,
    INITIAL_CONCEPTS_SYSTEM_PROMPT,
    CONCEPTS_SCHEMA,
    ADDITIONAL_CONCEPTS_USER_PROMPT,
    BRIEF_USER_PROMPT_TEMPLATE,
    BRIEF_SYSTEM_PROMPT_TEMPLATE,
)



# LLM Configuration
LLM_PROVIDER = "openai"
GENERATION_MODEL = "gpt-4.1"
LLM_TEMPERATURE = 0.8
LLM_MAX_TOKENS = 4000

# Workflow Defaults
PAST_CONTEXT_POSTS_LIMIT = 10  # Limit for context posts

# # --- Pydantic Schemas for LLM Outputs ---
# class ContentBriefSchema(BaseModel):
#     """
#     Defines the structure for a single content brief generated by the LLM.
#     """
#     brief_id: str = Field(..., description="Unique identifier for this brief (e.g., iteration number or UUID).")
#     topic: str = Field(..., description="The core subject or theme for the LinkedIn post.")
#     angle_or_hook: str = Field(..., description="A specific angle, perspective, or hook to make the post engaging.")
#     key_talking_points: List[str] = Field(..., description="Bulleted list of essential points or messages to include.")
#     call_to_action: Optional[str] = Field(None, description="A suggested call to action for the reader.")
#     suggested_hashtags: List[str] = Field(default_factory=list, description="Relevant hashtags to potentially include.")

# class ConceptSchema(BaseModel):
#     """
#     Defines the structure for content concepts generated during the ideation phase.
#     """
#     concept_id: str = Field(..., description="Unique identifier for this concept.")
#     title: str = Field(..., description="Short title or name for this concept.")
#     description: str = Field(..., description="Brief description of the concept.")
#     topic_area: str = Field(..., description="The broad topic area this concept fits into.")
#     target_audience: Optional[str] = Field(None, description="The intended audience for this concept.")
#     key_points: List[str] = Field(..., description="Key points or ideas to include in this concept.")
#     potential_angles: List[str] = Field(default_factory=list, description="Potential angles or perspectives for this concept.")

# class ConceptListSchema(BaseModel):
#     """
#     Defines the structure for a list of content concepts.
#     """
#     concepts: List[ConceptSchema] = Field(..., description="List of content concepts.")


workflow_graph_schema = {
  "nodes": {
        # --- 1. Input Node ---
        "input_node": {
            "node_id": "input_node",
            "node_name": "input_node",
            "node_config": {},
            "dynamic_output_schema": {
                    "fields": {
                        "customer_context_doc_configs": {
                            "type": "list",
                            "required": True,
                            "description": "List of document identifiers (namespace/docname pairs) for customer context like DNA, strategy docs."
                        },
                        
                        "past_context_posts_limit": { "type": "int", "required": False, "default": PAST_CONTEXT_POSTS_LIMIT, "description": f"Max number of combined posts (drafts + scraped) to use for context (default: {PAST_CONTEXT_POSTS_LIMIT})."},
                        "initial_brief_docname": { "type": "str", "required": True, "description": "Name of the initial brief document."},
                        "entity_username": {"type": "str", "required": True},
                        "user_instruction": {"type": "str", "required": False, "description": "Optional user instructions for concept generation."},
                    }
            }
        },

        # --- 2. Load Customer Context Documents and Scraped Posts (Single Node) ---
        "load_all_context_docs": {
            "node_id": "load_all_context_docs",
            "node_name": "load_customer_data",
            "node_config": {
                # Configure to load multiple documents based on the input list
                "load_configs_input_path": "customer_context_doc_configs", # Use the list from input node
                # Global defaults (can be overridden if needed per doc type via input structure)
                "global_is_shared": False,
                "global_is_system_entity": False,
                # "global_version_config": {"version": "default"},
                "global_schema_options": {"load_schema": False},
            },
        },

        # --- 3. Load Latest User Draft Posts ---
        "load_draft_posts": {
        "node_id": "load_draft_posts",
        "node_name": "load_multiple_customer_data", # Use the multi-loader node
        "node_config": {
            "namespace_pattern": CONTENT_DRAFT_NAMESPACE_TEMPLATE,
            "namespace_pattern_input_path": "entity_username",
            "include_shared": False,        # User-specific drafts only
            "include_user_specific": True,
            "include_system_entities": False,
            # Pagination and Sorting (Inputs mapped from state)
            "skip": 0,
            "limit": PAST_CONTEXT_POSTS_LIMIT, # Mapped from draft_posts_limit input
            "sort_by": "updated_at",
            "sort_order": "desc",

            # Loading options (default)
            "global_version_config": None, # Load active version if versioned
            "global_schema_options": {"load_schema": False,},

            # Output field name
            "output_field_name": "draft_posts" # The list will be under this key
        },
        #   "dynamic_output_schema": { # Define expected output
        #       "fields": {
        #           "draft_posts": { "type": "list", "required": True, "description": "List of loaded user draft posts." },
        #           "load_metadata": { "type": "dict", "required": True, "description": "Metadata about the loading operation."}
        #       }
        #   }
        # Reads: user_id (for filtering/permissions), draft_posts_limit (for config.limit) from state
        # Writes: draft_posts -> $graph_state
        },

        # --- 4. Merge Posts, Compute Limit, Prepare Generation Context ---
        "prepare_generation_context": {
        "node_id": "prepare_generation_context",
        "node_name": "merge_aggregate", # Use merge_aggregate to combine multiple sources
        "enable_node_fan_in": True, # Wait for all data loads before proceeding
        "node_config": {
            "operations": [
            # Operation 1: Merge Drafts and Scraped Posts and limit the result
            {
                "output_field_name": "final_merged_posts_for_prompt",
                # Order matters for priority (draft posts first, then scraped posts)
                "select_paths": ["draft_posts", "scraped_posts"], # Inputs from state
                "merge_strategy": {
                    "map_phase": {"unspecified_keys_strategy": "ignore"}, # Only care about merging lists
                    "reduce_phase": {
                        "default_reducer": "extend", # Combine the two lists
                        "error_strategy": "fail_node"
                    },
                    # Add transformation to limit the number of posts
                    "post_merge_transformations": {
                        "final_merged_posts_for_prompt": {
                            "operation_type": "limit_list", 
                            "operand_path": "past_context_posts_limit" # Get limit value from input
                        }
                    },
                    "transformation_error_strategy": "skip_operation"
                },
                "merge_each_object_in_selected_list": False # Treat lists as atomic values to be EXTENDed
            },
            ]
        },
        # Reads: loaded_draft_posts, loaded_scraped_posts, loaded_context_docs_list, weeks_to_generate, past_context_posts_limit (from state)
        # Writes: merged_data containing final_merged_posts_for_prompt and total_briefs_needed -> $graph_state
        },

        # --- 9. Construct Brief Prompt (Inside Map Branch) ---
        "construct_initial_concepts_prompt": {
            "node_id": "construct_initial_concepts_prompt",
            "node_name": "prompt_constructor",
            "enable_node_fan_in": True,  # Wait for all data loads before proceeding
            "node_config": {
                "prompt_templates": {
                    "initial_concepts_user_prompt": {
                        "id": "initial_concepts_user_prompt",
                        "template": INITIAL_CONCEPTS_USER_PROMPT,
                        "variables": {
                            "initial_brief": None,
                            "user_dna": None,
                            "merged_posts": None,
                            "user_instruction": None,
                        },
                        "construct_options": {
                            "initial_brief": "initial_brief",
                            "user_dna": "user_dna",
                            "merged_posts": "merged_posts",
                            "user_instruction": "user_instruction",
                        }
                    },
                    "concepts_system_prompt": {
                        "id": "concepts_system_prompt",
                        "template": INITIAL_CONCEPTS_SYSTEM_PROMPT,
                        "variables": { "schema": json.dumps(CONCEPTS_SCHEMA, indent=2) },
                        "construct_options": {}
                    }
                }
            },
        },


        # --- 10. Generate Brief (LLM - Inside Map Branch) ---
        "generate_concepts": {
            "node_id": "generate_concepts",
            "node_name": "llm",
            "node_config": {
                "llm_config": {
                    "model_spec": {"provider": LLM_PROVIDER, "model": GENERATION_MODEL},
                    "temperature": LLM_TEMPERATURE,
                    "max_tokens": LLM_MAX_TOKENS
                },
                "output_schema": {
                    "schema_definition": CONCEPTS_SCHEMA,
                    "convert_loaded_schema_to_pydantic": False
                },
            }
        },

        # --- 5. Store Concepts ---
        "store_concepts": {
            "node_id": "store_concepts",
            "node_name": "store_customer_data",
            "node_config": {
                    "global_versioning": {
                        "is_versioned": CONCEPT_IS_VERSIONED,
                        "operation": "upsert_versioned", # Must not exist yet
                    },
                    "store_configs": [
                        {
                            "input_field_path": "structured_output", # Field name in node input containing the value to save
                            "target_path": {
                                "filename_config": {
                                    "input_namespace_field_pattern": CONCEPT_NAMESPACE_TEMPLATE, 
                                    "input_namespace_field": "entity_username",
                                    "static_docname": CONCEPT_DOCNAME, # Field in node's input containing the value
                                }
                            },
                            "extra_fields": [
                                {
                                    # Required: Path to value in input data
                                    "src_path": "initial_brief.uuid",
                                    
                                    # Optional: Path where value should be placed in stored object
                                    # If not provided, defaults to last segment of src_path
                                    "dst_path": "brief_id"
                                },
                            ],
                            "generate_uuid": True,
                        }
                    ]
                }
            },

        # --- 6. Human Review ---
        "capture_user_choice": {
            "node_id": "capture_user_choice",
            "node_name": "hitl_node__default",
            "node_config": {}, # Config removed as base HITLNode ignores it
            "dynamic_output_schema": {
                "fields": {
                    "approval_status": { 
                        "type": "enum", 
                        "enum_values": ["regenerate", "restart_from_idea_generation", "select_concepts"],   # TODO: support select only 1 concept for now
                        "required": True, 
                        "description": "User action choice" 
                    },
                    "feedback_text": { 
                        "type": "str", 
                        "required": False, 
                        "description": "Optional feedback for regeneration" 
                    },
                    "selected_concepts": {
                        "type": "list",
                        "items_type": "str",
                        "required": False,
                        "description": "List of concept_ids the user selected if approval_status is 'select_concepts'"
                    }
                }
            }
        },

        # --- 7. Route Based on Approval ---
        "route_on_user_choice": {
            "node_id": "route_on_user_choice",
            "node_name": "router_node",
            "node_config": {
                "choices": ["construct_concepts_regeneration_prompt", "output_node", "filter_selected_concepts"],
                "allow_multiple": False,
                "choices_with_conditions": [
                {
                    "choice_id": "construct_concepts_regeneration_prompt",
                    "input_path": "user_choice_action",
                    "target_value": "regenerate"
                },
                {
                    "choice_id": "output_node",
                    "input_path": "user_choice_action",
                    "target_value": "restart_from_idea_generation"
                },
                {
                    "choice_id": "filter_selected_concepts",
                    "input_path": "user_choice_action",
                    "target_value": "select_concepts"
                }
                ]
            }
        },

        # --- Construct Additional Brief Prompt ---
        "construct_concepts_regeneration_prompt": {
            "node_id": "construct_concepts_regeneration_prompt",
            "node_name": "prompt_constructor",
            "node_config": {
                "prompt_templates": {
                "additional_brief_prompt": {
                    "id": "additional_brief_prompt",
                    "template": ADDITIONAL_CONCEPTS_USER_PROMPT,
                    "variables": {
                        "feedback_text": None
                    },
                    "construct_options": {
                        "feedback_text": "current_feedback_text"
                    }
                },
                }
            }
            # Reads: updated_brief from state
            # Writes: additional_brief_prompt, system_prompt
        },


        # --- Filter Selected Concepts ---
        "filter_selected_concepts": {
            "node_id": "filter_selected_concepts",
            "node_name": "filter_data",
            "node_config": {
                "targets": [
                    {
                        "filter_target": "concepts.concepts",  # Target the concepts list
                        "condition_groups": [
                            {
                                "conditions": [
                                    {
                                        "field": "concepts.concepts.concept_id",
                                        "operator": "equals_any_of",
                                        "value_path": "selected_concepts"
                                    }
                                ]
                            }
                        ],
                        "filter_mode": "allow"  # Only allow concepts that match the condition
                    },
                    # {
                    #     # Remove selected concepts from filtered data!
                    #     # NOTE: be careful about deleting 
                    #     "filter_target": "selected_concepts",  # Target the concepts list
                    #     "condition_groups": [
                    #         {
                    #             "conditions": [
                    #                 {
                    #                     "field": "selected_concepts",
                    #                     "operator": "is_not_empty",
                    #                 }
                    #             ]
                    #         }
                    #     ],
                    #     "filter_mode": "deny"  # Only allow concepts that match the condition
                    # }
                ]
            }
        },


        # --- 9. Construct Brief Prompt (Inside Map Branch) ---
        "construct_update_content_brief_prompt": {
            "node_id": "construct_update_content_brief_prompt",
            "node_name": "prompt_constructor",
            "node_config": {
                "prompt_templates": {
                    "brief_user_prompt": {
                        "id": "brief_user_prompt",
                        "template": BRIEF_USER_PROMPT_TEMPLATE,
                        "variables": {
                            "selected_concepts": None,
                            "user_dna": None,
                            "merged_posts": None,
                            "initial_brief": None
                        },
                        "construct_options": {
                            "selected_concepts": "selected_concepts.concepts",
                            "user_dna": "user_dna",
                            "merged_posts": "merged_posts",
                            "initial_brief": "initial_brief"
                        }
                    },
                    "brief_system_prompt": {
                        "id": "brief_system_prompt",
                        "template": BRIEF_SYSTEM_PROMPT_TEMPLATE,
                        "variables": { "schema": json.dumps(BRIEF_LLM_OUTPUT_SCHEMA, indent=2) },
                        "construct_options": {}
                    }
                }
            }
        },

        # --- 10. Generate Brief (LLM - Inside Map Branch) ---
        "generated_updated_content_brief": {
            "node_id": "generated_updated_content_brief",
            "node_name": "llm",
            "node_config": {
                "llm_config": {
                    "model_spec": {"provider": LLM_PROVIDER, "model": GENERATION_MODEL},
                    "temperature": LLM_TEMPERATURE,
                    "max_tokens": LLM_MAX_TOKENS
                },
                "output_schema": {
                    "schema_definition": BRIEF_LLM_OUTPUT_SCHEMA,
                    "convert_loaded_schema_to_pydantic": False
                },
            }
        },

        # --- 11. Store All Generated Briefs (After Map Completes) ---
        "save_updated_content_brief": {
            "node_id": "save_updated_content_brief",
            "node_name": "store_customer_data", # Store the final list
            "node_config": {
                "global_versioning": { "is_versioned": CONTENT_BRIEF_IS_VERSIONED, "operation": "upsert_versioned" },
                "global_is_shared": False,
                "store_configs": [
                    {
                        # Store the final content brief
                        "input_field_path": "updated_brief", # Mapped from LLM output
                        "target_path": {
                            "filename_config": {
                                "input_namespace_field_pattern": CONTENT_BRIEF_NAMESPACE_TEMPLATE, 
                                "input_namespace_field": "entity_username",
                                "input_docname_field": "brief_docname"
                            }
                        },
                        "versioning": {
                            "is_versioned": CONTENT_BRIEF_IS_VERSIONED,
                            "operation": "upsert_versioned",
                            "version": CONTENT_BRIEF_DEFAULT_VERSION
                        }
                    },
                    {
                        # Also store the selected concepts that were used
                        "input_field_path": "selected_concepts.concepts", # Mapped from filter_selected_concepts
                        "target_path": {
                            "filename_config": {
                                "input_namespace_field_pattern": CONCEPT_NAMESPACE_TEMPLATE, 
                                "input_namespace_field": "entity_username",
                                "static_docname": CONCEPT_DOCNAME, # Field in node's input containing the value
                            }
                        },
                        "extra_fields": [
                            {
                                # Required: Path to value in input data
                                "src_path": "initial_brief.uuid",
                                
                                # Optional: Path where value should be placed in stored object
                                # If not provided, defaults to last segment of src_path
                                "dst_path": "brief_id"
                            },
                        ],
                        "versioning": {
                            "is_versioned": CONCEPT_IS_VERSIONED,
                            "operation": "upsert_versioned",
                        }
                    }
                ],
            }
            # Reads: updated_brief, user_id (from state)
            # Writes: paths_processed
        },


        # --- 12. Output Node ---
        "output_node": {
            "node_id": "output_node",
            "node_name": "output_node",
            "node_config": {},
            # "dynamic_input_schema": { # Define expected final inputs
            #     "fields": {
            #         "final_briefs_list": { "type": "list", "required": True, "description": "The complete list of generated content briefs." },
            #         "brief_paths_processed": { "type": "list", "required": False, "description": "Confirmation/path from the storage operation." }
            #     }
            # }
            # Reads: updated_brief (mapped to final_briefs_list), paths_processed (mapped to save_confirmation)
        },




    },

    # --- Edges Defining Data Flow ---
    "edges": [
        # --- Initial Setup ---
        # Input -> State: Store initial inputs globally
        { "src_node_id": "input_node", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "customer_context_doc_configs", "dst_field": "customer_context_doc_configs" },
            { "src_field": "past_context_posts_limit", "dst_field": "past_context_posts_limit" },
            { "src_field": "initial_brief_docname", "dst_field": "initial_brief_docname" },
            { "src_field": "entity_username", "dst_field": "entity_username" },
            { "src_field": "user_instruction", "dst_field": "user_instruction" },
          ]
        },
        
        # Input -> Load operations
        { "src_node_id": "input_node", "dst_node_id": "load_all_context_docs", "mappings": [
            { "src_field": "customer_context_doc_configs", "dst_field": "customer_context_doc_configs" },
            { "src_field": "initial_brief_docname", "dst_field": "initial_brief_docname" },
            { "src_field": "entity_username", "dst_field": "entity_username" },
          ], "description": "Trigger context docs loading."
        },


        { "src_node_id": "input_node", "dst_node_id": "load_draft_posts",
            "mappings": [
                { "src_field": "entity_username", "dst_field": "entity_username" },
            ],
            },

        # --- State Updates from Loaders ---
        { "src_node_id": "load_all_context_docs", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "user_dna", "dst_field": "user_dna"},
            { "src_field": "initial_brief", "dst_field": "initial_brief"},
            { "src_field": "scraped_posts", "dst_field": "scraped_posts"}
          ]
        },

        { "src_node_id": "load_draft_posts", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "draft_posts", "dst_field": "draft_posts"}
          ]
        },

        { "src_node_id": "load_all_context_docs", "dst_node_id": "prepare_generation_context"},
        
        { "src_node_id": "load_draft_posts", "dst_node_id": "prepare_generation_context"},

        # --- Mapping State to Context Prep Node ---
        { "src_node_id": "$graph_state", "dst_node_id": "prepare_generation_context", "mappings": [
            { "src_field": "draft_posts", "dst_field": "draft_posts" },
            { "src_field": "scraped_posts", "dst_field": "scraped_posts" },
            { "src_field": "past_context_posts_limit", "dst_field": "past_context_posts_limit" },
        ]
        },

            # --- Map Iteration -> Construct Prompt (Private Edge) ---
        { "src_node_id": "prepare_generation_context", "dst_node_id": "construct_initial_concepts_prompt",
            "mappings": [
                { "src_field": "merged_data", "dst_field": "merged_posts" },
            ]
        },

        { "src_node_id": "prepare_generation_context", "dst_node_id": "$graph_state",
            "mappings": [
                { "src_field": "merged_data", "dst_field": "merged_posts" },
            ]
        },

        # --- Mapping State to Initial Concepts Prompt ---
        { "src_node_id": "$graph_state", "dst_node_id": "construct_initial_concepts_prompt", "mappings": [
            { "src_field": "user_dna", "dst_field": "user_dna" },
            { "src_field": "initial_brief", "dst_field": "initial_brief" },
            { "src_field": "user_instruction", "dst_field": "user_instruction" },
          ]
        },

        # --- Construct Prompt → Generate Concepts ---
        { "src_node_id": "construct_initial_concepts_prompt", "dst_node_id": "generate_concepts", "mappings": [
            { "src_field": "initial_concepts_user_prompt", "dst_field": "user_prompt"},
            { "src_field": "concepts_system_prompt", "dst_field": "system_prompt"}
          ], "description": "Send prompts to LLM for concept generation."
        },

        # --- State -> Generate Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "generate_concepts", "mappings": [
            { "src_field": "generate_concepts_messages_history", "dst_field": "messages_history"}
          ]
        },

        # --- Generate Concepts -> Store & State ---
        { "src_node_id": "generate_concepts", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "structured_output", "dst_field": "current_generated_concepts"},
            { "src_field": "current_messages", "dst_field": "generate_concepts_messages_history"}
          ]
        },

        { "src_node_id": "generate_concepts", "dst_node_id": "store_concepts", "mappings": [
            { "src_field": "structured_output", "dst_field": "structured_output"}
          ]
        },

        # --- State -> Store Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "store_concepts", "mappings": [
            { "src_field": "initial_brief", "dst_field": "initial_brief"},
            { "src_field": "entity_username", "dst_field": "entity_username"},
          ]
        },

        # --- Store Concepts -> User Choice ---
        { "src_node_id": "store_concepts", "dst_node_id": "capture_user_choice", "mappings": [
            { "src_field": "paths_processed", "dst_field": "draft_paths_processed"}
          ]
        },

        # --- State -> User Choice ---
        { "src_node_id": "$graph_state", "dst_node_id": "capture_user_choice", "mappings": [
            { "src_field": "current_generated_concepts", "dst_field": "concepts_for_review"}
          ]
        },

        # --- User Choice -> Route ---
        { "src_node_id": "capture_user_choice", "dst_node_id": "route_on_user_choice", "mappings": [
            { "src_field": "approval_status", "dst_field": "user_choice_action"},
          ]
        },

        # --- User Choice -> State ---
        { "src_node_id": "capture_user_choice", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "feedback_text", "dst_field": "current_feedback_text"},
            { "src_field": "selected_concepts", "dst_field": "user_selected_concepts"}
          ]
        },

        # --- Route -> Paths ---
        { "src_node_id": "route_on_user_choice", "dst_node_id": "construct_concepts_regeneration_prompt", "description": "Route to regenerate concepts if requested." },
        { "src_node_id": "route_on_user_choice", "dst_node_id": "output_node", "description": "Route to output if going back." },
        { "src_node_id": "route_on_user_choice", "dst_node_id": "filter_selected_concepts", "description": "Route to filter if concepts selected." },

        # --- Regeneration Prompt -> Generate Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "construct_concepts_regeneration_prompt", "mappings": [
            { "src_field": "current_feedback_text", "dst_field": "current_feedback_text"}
          ]},

        { "src_node_id": "construct_concepts_regeneration_prompt", "dst_node_id": "generate_concepts", "mappings": [
            { "src_field": "additional_brief_prompt", "dst_field": "user_prompt"}
          ]
        },

        # --- State -> Filter ---
        { "src_node_id": "$graph_state", "dst_node_id": "filter_selected_concepts", "mappings": [
            { "src_field": "current_generated_concepts", "dst_field": "concepts"},
            { "src_field": "user_selected_concepts", "dst_field": "selected_concepts"}
          ]
        },

        # --- Filter -> Update Content Brief Prompt ---
        { "src_node_id": "filter_selected_concepts", "dst_node_id": "construct_update_content_brief_prompt", "mappings": [
            { "src_field": "filtered_data", "dst_field": "selected_concepts"}
          ]
        },

        # --- Filter -> Save Updated Content Brief (to also save selected concepts) ---
        # NOTE: overwrites user choices with filtered concepts!
        { "src_node_id": "filter_selected_concepts", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "filtered_data", "dst_field": "selected_concepts"}
          ]
        },

        # --- State -> Update Content Brief Prompt ---
        { "src_node_id": "$graph_state", "dst_node_id": "construct_update_content_brief_prompt", "mappings": [
            { "src_field": "user_dna", "dst_field": "user_dna" },
            { "src_field": "initial_brief", "dst_field": "initial_brief"},
            { "src_field": "merged_posts", "dst_field": "merged_posts"}
          ]
        },

        # --- Update Content Brief Prompt -> Generate Updated Brief ---
        { "src_node_id": "construct_update_content_brief_prompt", "dst_node_id": "generated_updated_content_brief", "mappings": [
            { "src_field": "brief_user_prompt", "dst_field": "user_prompt"},
            { "src_field": "brief_system_prompt", "dst_field": "system_prompt"}
          ]
        },

        # --- Generate Updated Brief -> State ---
        { "src_node_id": "generated_updated_content_brief", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "structured_output", "dst_field": "updated_brief"},
            # { "src_field": "current_messages", "dst_field": "brief_messages_history"}
          ]
        },

        # --- Generate Updated Brief -> Save ---
        { "src_node_id": "generated_updated_content_brief", "dst_node_id": "save_updated_content_brief", "mappings": [
            { "src_field": "structured_output", "dst_field": "updated_brief"}
          ]
        },

        # --- State -> Save ---
        { "src_node_id": "$graph_state", "dst_node_id": "save_updated_content_brief", "mappings": [
            { "src_field": "initial_brief_docname", "dst_field": "brief_docname"},
            { "src_field": "initial_brief", "dst_field": "initial_brief"},
            { "src_field": "selected_concepts", "dst_field": "selected_concepts"},
            { "src_field": "entity_username", "dst_field": "entity_username"}
        ]},

        # --- Save -> Output ---
        { "src_node_id": "save_updated_content_brief", "dst_node_id": "output_node", "mappings": [
            { "src_field": "paths_processed", "dst_field": "brief_paths_processed"}
          ]
        },

        # --- State -> Output ---
        { "src_node_id": "$graph_state", "dst_node_id": "output_node", "mappings": [
            { "src_field": "updated_brief", "dst_field": "final_brief_content"},
            { "src_field": "selected_concepts", "dst_field": "selected_concepts"},
          ]
        },
    ],

    # --- Define Start and End ---
    "input_node_id": "input_node",
    "output_node_id": "output_node",

    # --- State Reducers ---
    "metadata": {
        "$graph_state": {
            "reducer": {
                # NOTE: If you set collect_values reducer here, it distorts / nests the concepts structure and fails the FILTER NODE!
                # "current_generated_concepts": "collect_values",
                "generate_concepts_messages_history": "add_messages",
                "generated_updated_content_brief_messages_history": "add_messages"
            }
        }
    }
}


# --- Test Execution Logic ---
async def main_test_idea_to_brief_workflow():
    """
    Test for Idea to Brief Workflow.
    
    This function sets up test data, executes the workflow, and validates the output.
    The workflow takes an initial brief, generates content concepts, allows for user selection,
    and then creates a refined content brief based on the selected concepts.
    """
    test_name = "Idea to Brief Workflow Test"
    print(f"--- Starting {test_name} --- ")

    # Example Inputs
    test_context_docs = [
        {
            "filename_config": {
                "input_namespace_field_pattern": USER_DNA_NAMESPACE_TEMPLATE, 
                "input_namespace_field": "entity_username",
                "static_docname": USER_DNA_DOCNAME,
            },
            "output_field_name": "user_dna"  # Field where the loaded DNA doc will be stored
        },
        {
            "filename_config": {
                "input_namespace_field_pattern": CONTENT_BRIEF_NAMESPACE_TEMPLATE, 
                "input_namespace_field": "entity_username",
                "input_docname_field": "initial_brief_docname",
            },
            "output_field_name": "initial_brief"  # Field where the loaded initial brief will be stored
        },
        {
            "filename_config": {
                "input_namespace_field_pattern": LINKEDIN_SCRAPING_NAMESPACE_TEMPLATE, 
                "input_namespace_field": "entity_username",
                "static_docname": LINKEDIN_POST_DOCNAME,
            },
            "output_field_name": "scraped_posts" # Expect output containing LinkedIn posts
        },
    ]
    
    brief_docname = "test_brief_1"
    test_entity_username = "test_entity"
    
    test_inputs = {
        "initial_brief_docname": brief_docname,
        "customer_context_doc_configs": test_context_docs,
        "past_context_posts_limit": 20,
        "entity_username": test_entity_username,
        "user_instruction": "Please generate concepts that focus on practical implementation and real-world examples, avoiding theoretical discussions."
    }
    # print(json.dumps(test_inputs, indent=4))
    # return

    # Define setup documents
    setup_docs = [
        # User DNA Document
        {
            'namespace': USER_DNA_NAMESPACE_TEMPLATE.format(item=test_entity_username), 
            'docname': USER_DNA_DOCNAME,
            'initial_data': {
                "professional_background": "Marketing executive with 15+ years experience in tech",
                "expertise_areas": ["Digital Marketing", "Brand Strategy", "Team Leadership"],
                "target_audience": "Marketing professionals and business leaders",
                "content_goals": "Establish thought leadership and drive engagement",
                "personal_style": "Conversational but authoritative",
                "personal_brand_statement": "Helping leaders navigate digital transformation through strategic marketing insights",
                "ideal_voice_tone": "Confident, insightful, and approachable"
            }, 
            'is_versioned': USER_DNA_IS_VERSIONED, 
            'is_shared': False,
            'initial_version': 'default'  # Required for versioned documents
        },
        # Initial Brief Document
        {
            'namespace': CONTENT_BRIEF_NAMESPACE_TEMPLATE.format(item=test_entity_username), 
            'docname': brief_docname,
            'initial_data': {
                "uuid": brief_docname,
                "title": "Building personal brand in the digital marketing landscape",
                "core_perspective": "How innovative leadership approaches can disrupt traditional marketing paradigms",
                "key_messages": [
                    "The intersection of personal branding and digital marketing strategy",
                    "Leadership principles that foster innovation in marketing teams",
                    "Case studies of industry disruption through personal brand leverage",
                    "Metrics that matter when measuring personal brand impact"
                ],
                "target_audience": {
                    "primary": "Marketing professionals looking to differentiate themselves",
                    "secondary": "Business leaders seeking marketing innovations"
                },
                "content_pillar": "Digital Transformation",
                "post_objectives": ["Educate audience", "Position as thought leader", "Drive engagement"],
                "tone_and_style": "Professional with authoritative insights, conversational yet data-backed",
                "call_to_action": "Connect with me to discuss how we can revolutionize your marketing approach",
                "hashtags": ["#PersonalBrand", "#MarketingInnovation", "#LeadershipStrategy", "#IndustryDisruption", "#DigitalMarketing"],
                "evidence_and_examples": ["Case study on Nike's digital transformation", "Insights from McKinsey's latest marketing report"],
                "structure_outline": {
                    "opening_hook": "In a digital landscape where everyone has a platform, how do you make your voice count?",
                    "common_misconception": "Many marketers believe personal branding is just about self-promotion",
                    "core_perspective": "Personal branding is actually about delivering consistent value to your specific audience",
                    "supporting_evidence": "Leaders who invest in their personal brand see 40% higher engagement rates",
                    "practical_framework": "The 3P approach: Purpose, Presence, and Persistence",
                    "strategic_takeaway": "Personal branding requires strategic alignment with broader business goals",
                    "engagement_question": "What's one aspect of your personal brand that differentiates you in your industry?"
                },
                "suggested_hook_options": [
                    "The digital marketing landscape changes daily, but one principle remains constant...",
                    "What if I told you most personal branding advice is fundamentally flawed?",
                    "Three years ago, I made a strategic personal branding decision that transformed my business..."
                ],
                "post_length": {
                    "min": 500,
                    "max": 800
                },
                "scheduled_date": "2023-07-01"
            }, 
            'initial_version': CONTENT_BRIEF_DEFAULT_VERSION,
            'is_versioned': CONTENT_BRIEF_IS_VERSIONED, 
            'is_shared': False
        },
        # Mock LinkedIn Scraped Posts
        {
            'namespace': LINKEDIN_SCRAPING_NAMESPACE_TEMPLATE.format(item=test_entity_username), 
            'docname': LINKEDIN_POST_DOCNAME,
            'initial_data': [
                {
                    "urn": "post-12345",
                    "text": "Excited to share my thoughts on digital marketing trends for 2023. The landscape is evolving rapidly with AI integration becoming mainstream. What trends are you most excited about? #DigitalMarketing #AIinMarketing #2023Trends",
                    "publish_date": "2023-05-15T10:00:00Z",
                    "reaction_count": 150,
                    "comment_count": 24
                },
                {
                    "urn": "post-67890",
                    "text": "Leadership in the age of remote work presents unique challenges. I've found that regular check-ins, clear expectations, and embracing flexibility have been key to maintaining team cohesion. What strategies have worked for your remote leadership? #RemoteWork #LeadershipTips #TeamManagement",
                    "publish_date": "2023-05-08T14:30:00Z",
                    "reaction_count": 210,
                    "comment_count": 32
                }
            ], 
            'is_versioned': False,
            'is_shared': False
        },
        # Mock Draft Posts
        {
            'namespace': CONTENT_DRAFT_NAMESPACE_TEMPLATE.format(item=test_entity_username), 
            'docname': CONTENT_DRAFT_DOCNAME.replace('{_uuid_}', 'draft-1'),
            'initial_data': {
                "title": "Thoughts on AI in Marketing",
                "content": "AI is transforming how we approach marketing campaigns. From personalized content to predictive analytics, the possibilities are endless. However, the human touch remains essential. How are you balancing AI and human creativity in your marketing strategy? #AIMarketing #MarketingStrategy #DigitalTransformation",
                "created_at": "2023-06-01T10:00:00Z",
                "updated_at": "2023-06-02T14:30:00Z",
                "status": "draft",
                "content_pillar": "Digital Transformation",
                "target_audience": "Marketing professionals",
                "key_messages": [
                    "AI enhances but doesn't replace human creativity",
                    "Personalization is key to modern marketing",
                    "Balance technology with authentic connection"
                ]
            }, 
            'is_versioned': CONTENT_DRAFT_IS_VERSIONED, 
            'is_shared': False,
            'initial_version': 'draft'
        },
        {
            'namespace': CONTENT_DRAFT_NAMESPACE_TEMPLATE.format(item=test_entity_username), 
            'docname': CONTENT_DRAFT_DOCNAME.replace('{_uuid_}', 'draft-2'),
            'initial_data': {
                "title": "Leadership Lessons from 2023",
                "content": "This year has taught me valuable lessons about remote leadership. Adaptability, empathy, and clear communication have been more important than ever. As we look ahead, I believe the hybrid workplace will continue to evolve. What leadership qualities do you think will be most crucial in the coming year? #LeadershipInsights #FutureOfWork #HybridWorkplace",
                "created_at": "2023-06-05T09:15:00Z",
                "updated_at": "2023-06-05T16:45:00Z",
                "status": "draft",
                "content_pillar": "Leadership Insights",
                "target_audience": "Team leaders and managers",
                "key_messages": [
                    "Adaptability is essential in uncertain times",
                    "Empathy forms the foundation of effective leadership",
                    "Communication must be intentional in remote settings"
                ]
            }, 
            'is_versioned': CONTENT_DRAFT_IS_VERSIONED, 
            'is_shared': False,
            'initial_version': 'draft'
        },
    ]

    # Define cleanup docs
    cleanup_docs = [
        {'namespace': USER_DNA_NAMESPACE_TEMPLATE.format(item=test_entity_username), 'docname': USER_DNA_DOCNAME, 'is_versioned': USER_DNA_IS_VERSIONED, 'is_shared': False},
        {'namespace': CONTENT_BRIEF_NAMESPACE_TEMPLATE.format(item=test_entity_username), 'docname': brief_docname, 'is_versioned': CONTENT_BRIEF_IS_VERSIONED, 'is_shared': False},
        {'namespace': CONCEPT_NAMESPACE_TEMPLATE.format(item=test_entity_username), 'docname': CONCEPT_DOCNAME.replace('{_uuid_}', '*'), 'is_versioned': CONCEPT_IS_VERSIONED, 'is_shared': False},
        {'namespace': CONTENT_DRAFT_NAMESPACE_TEMPLATE.format(item=test_entity_username), 'docname': CONTENT_DRAFT_DOCNAME.replace('{_uuid_}', 'draft-1'), 'is_versioned': CONTENT_DRAFT_IS_VERSIONED, 'is_shared': False},
        {'namespace': CONTENT_DRAFT_NAMESPACE_TEMPLATE.format(item=test_entity_username), 'docname': CONTENT_DRAFT_DOCNAME.replace('{_uuid_}', 'draft-2'), 'is_versioned': CONTENT_DRAFT_IS_VERSIONED, 'is_shared': False},
        {'namespace': LINKEDIN_SCRAPING_NAMESPACE_TEMPLATE.format(item=test_entity_username), 'docname': LINKEDIN_POST_DOCNAME, 'is_versioned': False, 'is_shared': False},
    ]

    # Predefined HITL inputs - leaving empty to allow for interactive testing
    # In actual testing, you can provide predefined inputs like:
    # {"approval_status": "select_concepts", "selected_concepts": ["concept_1", "concept_2"]}
    predefined_hitl_inputs = []
    
    # VALID HUMAN INPUTS FOR MANUAL TESTING:
    # {"approval_status": "select_concepts", "selected_concepts": ["concept_01"]}
    # {"approval_status": "regenerate", "feedback_text": "Please generate more contrarian concepts"}
    # {"approval_status": "restart_from_idea_generation"}

    # Output validation function
    async def validate_brief_output(outputs):
        """Validates the workflow output to ensure it meets expected structure and content requirements."""
        assert outputs is not None, "Validation Failed: Workflow returned no outputs."
        assert 'final_brief_content' in outputs, "Validation Failed: 'final_brief_content' missing."
        assert 'brief_paths_processed' in outputs, "Validation Failed: 'brief_paths_processed' missing."
        
        # Validate the content brief structure
        if 'final_brief_content' in outputs:
            brief = outputs['final_brief_content']
            # Check for required fields based on ContentBriefSchema in content_calendar_brief.py
            assert 'title' in brief, "Brief missing required field: title"
            assert 'content_pillar' in brief, "Brief missing required field: content_pillar"
            assert 'core_perspective' in brief, "Brief missing required field: core_perspective"
            assert 'target_audience' in brief and isinstance(brief['target_audience'], dict), "Brief missing or invalid field: target_audience"
            assert 'primary' in brief['target_audience'], "target_audience missing required field: primary"
            
            # Check for key list fields
            assert 'key_messages' in brief and isinstance(brief['key_messages'], list), "Brief missing or invalid field: key_messages"
            assert 'post_objectives' in brief and isinstance(brief['post_objectives'], list), "Brief missing or invalid field: post_objectives"
            assert 'hashtags' in brief and isinstance(brief['hashtags'], list), "Brief missing or invalid field: hashtags"
            
            # Check for structured objects
            assert 'structure_outline' in brief and isinstance(brief['structure_outline'], dict), "Brief missing or invalid field: structure_outline"
            assert 'post_length' in brief and isinstance(brief['post_length'], dict), "Brief missing or invalid field: post_length"
            
            print(f"✓ Final brief validated successfully with title: {brief.get('title', 'unknown')}")
        
        return True

    # Execute the test
    final_run_status_obj, final_run_outputs = await run_workflow_test(
        test_name=test_name,
        workflow_graph_schema=workflow_graph_schema,
        initial_inputs=test_inputs,
        expected_final_status=WorkflowRunStatus.COMPLETED,
        hitl_inputs=predefined_hitl_inputs,
        setup_docs=setup_docs,
        cleanup_docs=cleanup_docs,
        cleanup_docs_created_by_setup=False,
        validate_output_func=validate_brief_output,
        stream_intermediate_results=True,
        poll_interval_sec=5,
        timeout_sec=600
    )

    print(f"--- {test_name} Finished --- ")
    if final_run_outputs and 'final_brief_content' in final_run_outputs:
        brief = final_run_outputs['final_brief_content']
        print(f"Generated Brief Title: {brief.get('title')}")
        print(f"Generated Brief Core Perspective: {brief.get('core_perspective')}")
        print(f"Generated Brief Call to Action: {brief.get('call_to_action')}")
        print(f"Generated Brief Hashtags: {brief.get('hashtags')}")

if __name__ == "__main__":
    try:
        asyncio.run(main_test_idea_to_brief_workflow())
    except KeyboardInterrupt:
        print("\nExecution interrupted.")
    except Exception as e:
        print(f"\nError running test: {e}")

