# User DNA
LINKEDIN_USER_DNA_DOCNAME = "linkedin_executive_dna_doc"
LINKEDIN_USER_DNA_NAMESPACE_TEMPLATE = "linkedin_executive_strategy_{item}"
LINKEDIN_USER_DNA_IS_VERSIONED = True
LINKEDIN_USER_DNA_IS_SHARED = False
LINKEDIN_USER_DNA_IS_SYSTEM_ENTITY = False

LINKEDIN_CONTENT_PLAYBOOK_DOCNAME = "linkedin_content_playbook_doc"
LINKEDIN_CONTENT_PLAYBOOK_NAMESPACE_TEMPLATE = "linkedin_executive_strategy_{item}"
LINKEDIN_CONTENT_PLAYBOOK_IS_VERSIONED = True
LINKEDIN_CONTENT_PLAYBOOK_IS_SHARED = False
LINKEDIN_CONTENT_PLAYBOOK_IS_SYSTEM_ENTITY = False

LINKEDIN_DEEP_RESEARCH_REPORT_DOCNAME = "linkedin_deep_research_report_doc"
LINKEDIN_DEEP_RESEARCH_REPORT_NAMESPACE_TEMPLATE = "linkedin_deep_research_report_{item}"
LINKEDIN_DEEP_RESEARCH_REPORT_IS_VERSIONED = False
LINKEDIN_DEEP_RESEARCH_REPORT_IS_SHARED = False
LINKEDIN_DEEP_RESEARCH_REPORT_IS_SYSTEM_ENTITY = False

# LinkedIn Content Diagnostic Report
LINKEDIN_CONTENT_DIAGNOSTIC_REPORT_DOCNAME = "linkedin_content_diagnostic_report_doc"
LINKEDIN_CONTENT_DIAGNOSTIC_REPORT_NAMESPACE_TEMPLATE = "linkedin_content_diagnostic_{item}"
LINKEDIN_CONTENT_DIAGNOSTIC_REPORT_IS_VERSIONED = False
LINKEDIN_CONTENT_DIAGNOSTIC_REPORT_IS_SHARED = False
LINKEDIN_CONTENT_DIAGNOSTIC_REPORT_IS_SYSTEM_ENTITY = False

# LinkedIn Uploaded Files
LINKEDIN_USER_AI_VISIBILITY_RAW_DATA_DOCNAME = "linkedin_user_ai_visibility_raw_data_{_uuid_}"
LINKEDIN_UPLOADED_FILES_DOCNAME = ""
LINKEDIN_UPLOADED_FILES_NAMESPACE_TEMPLATE = "linkedin_uploaded_files_{item}"
LINKEDIN_UPLOADED_FILES_IS_VERSIONED = False
LINKEDIN_UPLOADED_FILES_IS_SHARED = False
LINKEDIN_UPLOADED_FILES_IS_SYSTEM_ENTITY = False

# LinkedIn User Profile
LINKEDIN_USER_PROFILE_DOCNAME = "linkedin_executive_profile_doc"
LINKEDIN_USER_PROFILE_NAMESPACE_TEMPLATE = "linkedin_executive_profile_namespace_{item}"
LINKEDIN_USER_PROFILE_IS_VERSIONED = True
LINKEDIN_USER_PROFILE_IS_SHARED = False
LINKEDIN_USER_PROFILE_IS_SYSTEM_ENTITY = False

# LinkedIn Content Analysis
LINKEDIN_CONTENT_ANALYSIS_DOCNAME = "linkedin_content_analysis_doc"
LINKEDIN_CONTENT_ANALYSIS_NAMESPACE_TEMPLATE = "linkedin_executive_analysis_{item}"
LINKEDIN_CONTENT_ANALYSIS_IS_VERSIONED = False
LINKEDIN_CONTENT_ANALYSIS_IS_SHARED = False
LINKEDIN_CONTENT_ANALYSIS_IS_SYSTEM_ENTITY = False

# LinkedIn Scraped Profile
LINKEDIN_SCRAPED_PROFILE_DOCNAME = "linkedin_scraped_profile_doc"
LINKEDIN_SCRAPED_PROFILE_RAW_DOCNAME = "linkedin_scraped_profile_raw_doc"
LINKEDIN_SCRAPED_PROFILE_NAMESPACE_TEMPLATE = "linkedin_scraping_results_{item}"
LINKEDIN_SCRAPED_PROFILE_IS_VERSIONED = False
LINKEDIN_SCRAPED_PROFILE_IS_SHARED = False
LINKEDIN_SCRAPED_PROFILE_IS_SYSTEM_ENTITY = False

# LinkedIn Scraped Posts
LINKEDIN_SCRAPED_POSTS_DOCNAME = "linkedin_scraped_posts_doc"
LINKEDIN_SCRAPED_POSTS_RAW_DOCNAME = "linkedin_scraped_posts_raw_doc"
LINKEDIN_SCRAPED_POSTS_NAMESPACE_TEMPLATE = "linkedin_scraping_results_{item}"
LINKEDIN_SCRAPED_POSTS_IS_VERSIONED = False
LINKEDIN_SCRAPED_POSTS_IS_SHARED = False
LINKEDIN_SCRAPED_POSTS_IS_SYSTEM_ENTITY = False

# LinkedIn Brief
LINKEDIN_BRIEF_DOCNAME = "linkedin_brief_{item}"
LINKEDIN_BRIEF_NAMESPACE_TEMPLATE = "linkedin_content_briefs_{item}"
LINKEDIN_BRIEF_IS_VERSIONED = True
LINKEDIN_BRIEF_IS_SHARED = False
LINKEDIN_BRIEF_IS_SYSTEM_ENTITY = False

# LinkedIn Draft
LINKEDIN_DRAFT_DOCNAME = "linkedin_draft_{item}"
LINKEDIN_DRAFT_NAMESPACE_TEMPLATE = "linkedin_post_drafts_{item}"
LINKEDIN_DRAFT_IS_VERSIONED = True
LINKEDIN_DRAFT_IS_SHARED = False
LINKEDIN_DRAFT_IS_SYSTEM_ENTITY = False

# LinkedIn Idea
LINKEDIN_IDEA_DOCNAME = "linkedin_idea_{_uuid_}"
LINKEDIN_IDEA_NAMESPACE_TEMPLATE = "linkedin_content_ideas_{item}"
LINKEDIN_IDEA_IS_VERSIONED = True
LINKEDIN_IDEA_IS_SHARED = False
LINKEDIN_IDEA_IS_SYSTEM_ENTITY = False

# LinkedIn User Web Audit
# LINKEDIN_USER_WEB_AUDIT_DOCNAME = "linkedin_executive_web_audit_doc"
# LINKEDIN_USER_WEB_AUDIT_NAMESPACE_TEMPLATE = "linkedin_executive_analysis_{item}"
# LINKEDIN_USER_WEB_AUDIT_IS_VERSIONED = False
# LINKEDIN_USER_WEB_AUDIT_IS_SHARED = False
# LINKEDIN_USER_WEB_AUDIT_IS_SYSTEM_ENTITY = False

# LinkedIn User AI Visibility Test
LINKEDIN_USER_AI_VISIBILITY_TEST_DOCNAME = "linkedin_executive_ai_visibility_test_doc"
LINKEDIN_USER_AI_VISIBILITY_TEST_NAMESPACE_TEMPLATE = "linkedin_executive_analysis_{item}"
LINKEDIN_USER_AI_VISIBILITY_TEST_IS_VERSIONED = False
LINKEDIN_USER_AI_VISIBILITY_TEST_IS_SHARED = False
LINKEDIN_USER_AI_VISIBILITY_TEST_IS_SYSTEM_ENTITY = False

# # LinkedIn Writing Style
# LINKEDIN_WRITING_STYLE_DOCNAME = "linkedin_executive_writing_style_doc"
# LINKEDIN_WRITING_STYLE_NAMESPACE_TEMPLATE = "linkedin_executive_profile_namespace_{item}"
# LINKEDIN_WRITING_STYLE_IS_VERSIONED = True
# LINKEDIN_WRITING_STYLE_IS_SHARED = False
# LINKEDIN_WRITING_STYLE_IS_SYSTEM_ENTITY = False

# LinkedIn System Strategy Documents
LINKEDIN_METHODOLOGY_IMPLEMENTATION_DOCNAME = "linkedin_methodology_implementation_ai_copilot"
LINKEDIN_METHODOLOGY_IMPLEMENTATION_NAMESPACE_TEMPLATE = "linkedin_system_strategy_docs_namespace"
LINKEDIN_METHODOLOGY_IMPLEMENTATION_IS_SHARED = True
LINKEDIN_METHODOLOGY_IMPLEMENTATION_IS_VERSIONED = False
LINKEDIN_METHODOLOGY_IMPLEMENTATION_IS_SYSTEM_ENTITY = True

LINKEDIN_BUILDING_BLOCKS_DOCNAME = "linkedin_building_blocks_content_methodology"
LINKEDIN_BUILDING_BLOCKS_NAMESPACE_TEMPLATE = "linkedin_system_strategy_docs_namespace"
LINKEDIN_BUILDING_BLOCKS_IS_SHARED = True
LINKEDIN_BUILDING_BLOCKS_IS_VERSIONED = False
LINKEDIN_BUILDING_BLOCKS_IS_SYSTEM_ENTITY = True

LINKEDIN_POST_EVALUATION_DOCNAME = "linkedin_post_evaluation_framework"
LINKEDIN_POST_EVALUATION_NAMESPACE_TEMPLATE = "linkedin_system_strategy_docs_namespace"
LINKEDIN_POST_EVALUATION_IS_SHARED = True
LINKEDIN_POST_EVALUATION_IS_VERSIONED = False
LINKEDIN_POST_EVALUATION_IS_SYSTEM_ENTITY = True

LINKEDIN_POST_SCORING_DOCNAME = "linkedin_post_scoring_framework"
LINKEDIN_POST_SCORING_NAMESPACE_TEMPLATE = "linkedin_system_strategy_docs_namespace"
LINKEDIN_POST_SCORING_IS_SHARED = True
LINKEDIN_POST_SCORING_IS_VERSIONED = False
LINKEDIN_POST_SCORING_IS_SYSTEM_ENTITY = True

LINKEDIN_CONTENT_OPTIMIZATION_DOCNAME = "linkedin_content_optimization_guide"
LINKEDIN_CONTENT_OPTIMIZATION_NAMESPACE_TEMPLATE = "linkedin_system_strategy_docs_namespace"
LINKEDIN_CONTENT_OPTIMIZATION_IS_SHARED = True
LINKEDIN_CONTENT_OPTIMIZATION_IS_VERSIONED = False
LINKEDIN_CONTENT_OPTIMIZATION_IS_SYSTEM_ENTITY = True

# LinkedIn Playbook System Document
LINKEDIN_PLAYBOOK_SYSTEM_DOCUMENT_DOCNAME = ""
LINKEDIN_PLAYBOOK_SYSTEM_DOCUMENT_NAMESPACE_TEMPLATE = "linkedin_playbook_sys"
LINKEDIN_PLAYBOOK_SYSTEM_DOCUMENT_IS_VERSIONED = False
LINKEDIN_PLAYBOOK_SYSTEM_DOCUMENT_IS_SHARED = True
LINKEDIN_PLAYBOOK_SYSTEM_DOCUMENT_IS_SYSTEM_ENTITY = True








# Blog Posts
# BLOG_SCRAPED_POSTS_DOCNAME = "blog_scraped_posts_doc"
# BLOG_SCRAPED_POSTS_RAW_DOCNAME = "blog_scraped_posts_raw_doc"
# BLOG_SCRAPED_POSTS_NAMESPACE_TEMPLATE = "blog_scraped_posts_{item}"
# BLOG_SCRAPED_POSTS_IS_VERSIONED = False
# BLOG_SCRAPED_POSTS_IS_SHARED = False
# BLOG_SCRAPED_POSTS_IS_SYSTEM_ENTITY = False

# Blog Classified Posts
BLOG_CLASSIFIED_POSTS_DOCNAME = "blog_classified_posts_doc"
BLOG_CLASSIFIED_POSTS_RAW_DOCNAME = "blog_classified_posts_raw_doc"
BLOG_CLASSIFIED_POSTS_NAMESPACE_TEMPLATE = "blog_classified_posts_{item}"
BLOG_CLASSIFIED_POSTS_IS_VERSIONED = False
BLOG_CLASSIFIED_POSTS_IS_SHARED = False
BLOG_CLASSIFIED_POSTS_IS_SYSTEM_ENTITY = False

# Blog Company Profile
BLOG_COMPANY_DOCNAME = "blog_company_doc"
BLOG_COMPANY_NAMESPACE_TEMPLATE = "blog_company_profile_{item}"
BLOG_COMPANY_IS_VERSIONED = False
BLOG_COMPANY_IS_SHARED = False
BLOG_COMPANY_IS_SYSTEM_ENTITY = False

# Blog Content Strategy
BLOG_CONTENT_STRATEGY_DOCNAME = "blog_content_playbook_doc"
BLOG_CONTENT_STRATEGY_NAMESPACE_TEMPLATE = "blog_company_strategy_{item}"
BLOG_CONTENT_STRATEGY_IS_VERSIONED = True
BLOG_CONTENT_STRATEGY_IS_SHARED = False
BLOG_CONTENT_STRATEGY_IS_SYSTEM_ENTITY = False

# Blog SEO Audit
BLOG_TECHNICAL_ANALYSIS_DOCNAME = "blog_technical_analysis_doc"
BLOG_TECHNICAL_ANALYSIS_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
BLOG_TECHNICAL_ANALYSIS_IS_VERSIONED = False
BLOG_TECHNICAL_ANALYSIS_IS_SHARED = False
BLOG_TECHNICAL_ANALYSIS_IS_SYSTEM_ENTITY = False

# Blog AI Visibility Test
BLOG_AI_VISIBILITY_TEST_DOCNAME = "blog_ai_visibility_test_doc"
BLOG_AI_VISIBILITY_TEST_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
BLOG_AI_VISIBILITY_TEST_IS_VERSIONED = False
BLOG_AI_VISIBILITY_TEST_IS_SHARED = False
BLOG_AI_VISIBILITY_TEST_IS_SYSTEM_ENTITY = False

# Blog Company AI Visibility Test
BLOG_COMPANY_AI_VISIBILITY_TEST_DOCNAME = "blog_company_ai_baseline_doc"  ##check this
BLOG_COMPANY_AI_VISIBILITY_TEST_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
BLOG_COMPANY_AI_VISIBILITY_TEST_IS_VERSIONED = False
BLOG_COMPANY_AI_VISIBILITY_TEST_IS_SHARED = False
BLOG_COMPANY_AI_VISIBILITY_TEST_IS_SYSTEM_ENTITY = False

# Blog Competitor Content Analysis
BLOG_COMPETITOR_CONTENT_ANALYSIS_DOCNAME = "blog_competitor_content_analysis_{item}"
BLOG_COMPETITOR_CONTENT_ANALYSIS_NAMESPACE_TEMPLATE = "blog_competitor_content_analysis_namespace_{item}"
BLOG_COMPETITOR_CONTENT_ANALYSIS_IS_VERSIONED = False
BLOG_COMPETITOR_CONTENT_ANALYSIS_IS_SHARED = False
BLOG_COMPETITOR_CONTENT_ANALYSIS_IS_SYSTEM_ENTITY = False

# LinkedIn Uploaded Files
BLOG_AI_VISIBILITY_RAW_DATA_DOCNAME = "blog_ai_visibility_raw_data_{_uuid_}"
BLOG_UPLOADED_FILES_DOCNAME = ""
BLOG_UPLOADED_FILES_NAMESPACE_TEMPLATE = "blog_uploaded_files_{item}"
BLOG_UPLOADED_FILES_IS_VERSIONED = False
BLOG_UPLOADED_FILES_IS_SHARED = False
BLOG_UPLOADED_FILES_IS_SYSTEM_ENTITY = False

# Blog Content Analysis
BLOG_CONTENT_PORTFOLIO_ANALYSIS_DOCNAME = "blog_content_portfolio_analysis_doc"
BLOG_CONTENT_PORTFOLIO_ANALYSIS_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
BLOG_CONTENT_PORTFOLIO_ANALYSIS_IS_VERSIONED = False
BLOG_CONTENT_PORTFOLIO_ANALYSIS_IS_SHARED = False
BLOG_CONTENT_PORTFOLIO_ANALYSIS_IS_SYSTEM_ENTITY = False

BLOG_CONTENT_ANALYSIS_DOCNAME = "blog_content_analysis_doc"
BLOG_CONTENT_ANALYSIS_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
BLOG_CONTENT_ANALYSIS_IS_VERSIONED = False
BLOG_CONTENT_ANALYSIS_IS_SHARED = False
BLOG_CONTENT_ANALYSIS_IS_SYSTEM_ENTITY = False

BLOG_COMPANY_ANALYSIS_DOCNAME = "blog_company_analysis_doc"
BLOG_COMPANY_ANALYSIS_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
BLOG_COMPANY_ANALYSIS_IS_VERSIONED = False
BLOG_COMPANY_ANALYSIS_IS_SHARED = False
BLOG_COMPANY_ANALYSIS_IS_SYSTEM_ENTITY = False

# Blog Competitor AI Visibility Test
BLOG_COMPETITOR_AI_VISIBILITY_TEST_DOCNAME = "blog_competitor_ai_visibility_test_{item}"
BLOG_COMPETITOR_AI_VISIBILITY_TEST_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
BLOG_COMPETITOR_AI_VISIBILITY_TEST_IS_VERSIONED = False
BLOG_COMPETITOR_AI_VISIBILITY_TEST_IS_SHARED = False
BLOG_COMPETITOR_AI_VISIBILITY_TEST_IS_SYSTEM_ENTITY = False

# Blog Deep Research Report
BLOG_DEEP_RESEARCH_REPORT_DOCNAME = "blog_deep_research_report_doc"
BLOG_DEEP_RESEARCH_REPORT_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
BLOG_DEEP_RESEARCH_REPORT_IS_VERSIONED = False
BLOG_DEEP_RESEARCH_REPORT_IS_SHARED = False
BLOG_DEEP_RESEARCH_REPORT_IS_SYSTEM_ENTITY = False

# Blog Content Diagnostic Report
BLOG_CONTENT_DIAGNOSTIC_REPORT_DOCNAME = "blog_content_diagnostic_report_doc"
BLOG_CONTENT_DIAGNOSTIC_REPORT_NAMESPACE_TEMPLATE = "blog_content_diagnostic_report_{item}"
BLOG_CONTENT_DIAGNOSTIC_REPORT_IS_VERSIONED = False
BLOG_CONTENT_DIAGNOSTIC_REPORT_IS_SHARED = False
BLOG_CONTENT_DIAGNOSTIC_REPORT_IS_SYSTEM_ENTITY = False

# Blog Query Management Dashboard
BLOG_QUERY_MANAGEMENT_DASHBOARD_DOCNAME = "blog_query_management_dashboard_doc"
BLOG_QUERY_MANAGEMENT_DASHBOARD_NAMESPACE_TEMPLATE = "blog_ai_query_tracking_{item}"
BLOG_QUERY_MANAGEMENT_DASHBOARD_IS_VERSIONED = True
BLOG_QUERY_MANAGEMENT_DASHBOARD_IS_SHARED = False
BLOG_QUERY_MANAGEMENT_DASHBOARD_IS_SYSTEM_ENTITY = False

# Blog Weekly AI Visibility Report
BLOG_WEEKLY_AI_VISIBILITY_REPORT_DOCNAME = "blog_weekly_ai_visibility_report_doc"
BLOG_WEEKLY_AI_VISIBILITY_REPORT_NAMESPACE_TEMPLATE = "blog_ai_query_tracking_{item}"
BLOG_WEEKLY_AI_VISIBILITY_REPORT_IS_VERSIONED = True
BLOG_WEEKLY_AI_VISIBILITY_REPORT_IS_SHARED = False
BLOG_WEEKLY_AI_VISIBILITY_REPORT_IS_SYSTEM_ENTITY = False

# Blog Query Performance Summary
BLOG_QUERY_PERFORMANCE_SUMMARY_DOCNAME = "blog_query_performance_summary_doc"
BLOG_QUERY_PERFORMANCE_SUMMARY_NAMESPACE_TEMPLATE = "blog_ai_query_tracking_{item}"
BLOG_QUERY_PERFORMANCE_SUMMARY_IS_VERSIONED = True
BLOG_QUERY_PERFORMANCE_SUMMARY_IS_SHARED = False
BLOG_QUERY_PERFORMANCE_SUMMARY_IS_SYSTEM_ENTITY = False

# Blog User Schedule Config
BLOG_USER_SCHEDULE_CONFIG_DOCNAME = "blog_user_schedule_config_doc"
BLOG_USER_SCHEDULE_CONFIG_NAMESPACE_TEMPLATE = "blog_spark_delivery_{item}"
BLOG_USER_SCHEDULE_CONFIG_IS_VERSIONED = True
BLOG_USER_SCHEDULE_CONFIG_IS_SHARED = False
BLOG_USER_SCHEDULE_CONFIG_IS_SYSTEM_ENTITY = False

# Blog Spark Content Card
BLOG_SPARK_CONTENT_CARD_DOCNAME = "blog_spark_content_card_{_uuid_}"
BLOG_SPARK_CONTENT_CARD_NAMESPACE_TEMPLATE = "blog_spark_delivery_{item}"
BLOG_SPARK_CONTENT_CARD_IS_VERSIONED = True
BLOG_SPARK_CONTENT_CARD_IS_SHARED = False
BLOG_SPARK_CONTENT_CARD_IS_SYSTEM_ENTITY = False

# Blog Topic Ideas Card
BLOG_TOPIC_IDEAS_CARD_DOCNAME = "blog_topic_ideas_{_uuid_}"
BLOG_TOPIC_IDEAS_CARD_NAMESPACE_TEMPLATE = "blog_ideas_namespace_{item}"
BLOG_TOPIC_IDEAS_CARD_IS_VERSIONED = True
BLOG_TOPIC_IDEAS_CARD_IS_SHARED = False
BLOG_TOPIC_IDEAS_CARD_IS_SYSTEM_ENTITY = False

# Blog Content Brief
BLOG_CONTENT_BRIEF_DOCNAME = "blog_content_brief_{item}"
BLOG_CONTENT_BRIEF_NAMESPACE_TEMPLATE = "blog_brief_namespace_{item}"
BLOG_CONTENT_BRIEF_IS_VERSIONED = True
BLOG_CONTENT_BRIEF_IS_SHARED = False
BLOG_CONTENT_BRIEF_IS_SYSTEM_ENTITY = False

# Blog Post
BLOG_POST_DOCNAME = "blog_post_draft_{item}"
BLOG_POST_NAMESPACE_TEMPLATE = "blog_posts_draft_namespace_{item}"
BLOG_POST_IS_VERSIONED = True
BLOG_POST_IS_SHARED = False
BLOG_POST_IS_SYSTEM_ENTITY = False

# Blog SEO Best Practices (System Document)
BLOG_SEO_BEST_PRACTICES_DOCNAME = "seo_best_practices_doc"
BLOG_SEO_BEST_PRACTICES_NAMESPACE_TEMPLATE = "blog_seo_guidelines"
BLOG_SEO_BEST_PRACTICES_IS_VERSIONED = True
BLOG_SEO_BEST_PRACTICES_IS_SHARED = True
BLOG_SEO_BEST_PRACTICES_IS_SYSTEM_ENTITY = True

# Blog Playbook System Document
BLOG_PLAYBOOK_SYSTEM_DOCUMENT_DOCNAME = ""
BLOG_PLAYBOOK_SYSTEM_DOCUMENT_NAMESPACE_TEMPLATE = "blog_playbook_sys"
BLOG_PLAYBOOK_SYSTEM_DOCUMENT_IS_VERSIONED = True
BLOG_PLAYBOOK_SYSTEM_DOCUMENT_IS_SHARED = True
BLOG_PLAYBOOK_SYSTEM_DOCUMENT_IS_SYSTEM_ENTITY = True


# ============================================
# EXTERNAL RESEARCH DOCUMENTS
# ============================================

# External Research Report
EXTERNAL_RESEARCH_REPORT_NAMESPACE_TEMPLATE = "external_research_reports_{item}"

# ============================================
# LITE VERSIONS FOR CONTENT DIAGNOSTICS
# ============================================

# LinkedIn LITE Documents
LITE_LINKEDIN_USER_PROFILE_DOCNAME = "lite_linkedin_executive_profile_doc"
LITE_LINKEDIN_USER_PROFILE_NAMESPACE_TEMPLATE = "linkedin_executive_profile_namespace_{item}"
LITE_LINKEDIN_USER_PROFILE_IS_VERSIONED = True
LITE_LINKEDIN_USER_PROFILE_IS_SHARED = False
LITE_LINKEDIN_USER_PROFILE_IS_SYSTEM_ENTITY = False

LITE_LINKEDIN_SCRAPED_PROFILE_DOCNAME = "lite_linkedin_scraped_profile_doc"
LITE_LINKEDIN_SCRAPED_PROFILE_RAW_DOCNAME = "lite_linkedin_scraped_profile_raw_doc"
LITE_LINKEDIN_SCRAPED_PROFILE_NAMESPACE_TEMPLATE = "linkedin_scraping_results_{item}"
LITE_LINKEDIN_SCRAPED_PROFILE_IS_VERSIONED = False
LITE_LINKEDIN_SCRAPED_PROFILE_IS_SHARED = False
LITE_LINKEDIN_SCRAPED_PROFILE_IS_SYSTEM_ENTITY = False

LITE_LINKEDIN_SCRAPED_POSTS_DOCNAME = "lite_linkedin_scraped_posts_doc"
LITE_LINKEDIN_SCRAPED_POSTS_RAW_DOCNAME = "lite_linkedin_scraped_posts_raw_doc"
LITE_LINKEDIN_SCRAPED_POSTS_NAMESPACE_TEMPLATE = "linkedin_scraping_results_{item}"
LITE_LINKEDIN_SCRAPED_POSTS_IS_VERSIONED = False
LITE_LINKEDIN_SCRAPED_POSTS_IS_SHARED = False
LITE_LINKEDIN_SCRAPED_POSTS_IS_SYSTEM_ENTITY = False

LITE_LINKEDIN_USER_AI_VISIBILITY_TEST_DOCNAME = "lite_linkedin_executive_ai_visibility_test_doc"
LITE_LINKEDIN_USER_AI_VISIBILITY_TEST_NAMESPACE_TEMPLATE = "linkedin_executive_analysis_{item}"
LITE_LINKEDIN_USER_AI_VISIBILITY_TEST_IS_VERSIONED = False
LITE_LINKEDIN_USER_AI_VISIBILITY_TEST_IS_SHARED = False
LITE_LINKEDIN_USER_AI_VISIBILITY_TEST_IS_SYSTEM_ENTITY = False

LITE_LINKEDIN_USER_AI_VISIBILITY_RAW_DATA_DOCNAME = "lite_linkedin_user_ai_visibility_raw_data_{_uuid_}"
LITE_LINKEDIN_UPLOADED_FILES_DOCNAME = ""
LITE_LINKEDIN_UPLOADED_FILES_NAMESPACE_TEMPLATE = "linkedin_uploaded_files_{item}"
LITE_LINKEDIN_UPLOADED_FILES_IS_VERSIONED = False
LITE_LINKEDIN_UPLOADED_FILES_IS_SHARED = False
LITE_LINKEDIN_UPLOADED_FILES_IS_SYSTEM_ENTITY = False

LITE_LINKEDIN_CONTENT_ANALYSIS_DOCNAME = "lite_linkedin_content_analysis_doc"
LITE_LINKEDIN_CONTENT_ANALYSIS_NAMESPACE_TEMPLATE = "linkedin_executive_analysis_{item}"
LITE_LINKEDIN_CONTENT_ANALYSIS_IS_VERSIONED = False
LITE_LINKEDIN_CONTENT_ANALYSIS_IS_SHARED = False
LITE_LINKEDIN_CONTENT_ANALYSIS_IS_SYSTEM_ENTITY = False

LITE_LINKEDIN_DEEP_RESEARCH_REPORT_DOCNAME = "lite_linkedin_deep_research_report_doc"
LITE_LINKEDIN_DEEP_RESEARCH_REPORT_NAMESPACE_TEMPLATE = "linkedin_deep_research_report_{item}"
LITE_LINKEDIN_DEEP_RESEARCH_REPORT_IS_VERSIONED = False
LITE_LINKEDIN_DEEP_RESEARCH_REPORT_IS_SHARED = False
LITE_LINKEDIN_DEEP_RESEARCH_REPORT_IS_SYSTEM_ENTITY = False

LITE_LINKEDIN_CONTENT_DIAGNOSTIC_REPORT_DOCNAME = "lite_linkedin_content_diagnostic_report_doc"
LITE_LINKEDIN_CONTENT_DIAGNOSTIC_REPORT_NAMESPACE_TEMPLATE = "linkedin_content_diagnostic_{item}"
LITE_LINKEDIN_CONTENT_DIAGNOSTIC_REPORT_IS_VERSIONED = False
LITE_LINKEDIN_CONTENT_DIAGNOSTIC_REPORT_IS_SHARED = False
LITE_LINKEDIN_CONTENT_DIAGNOSTIC_REPORT_IS_SYSTEM_ENTITY = False

# Blog LITE Documents
LITE_BLOG_CONTENT_ANALYSIS_DOCNAME = "lite_blog_content_analysis_doc"
LITE_BLOG_CONTENT_ANALYSIS_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
LITE_BLOG_CONTENT_ANALYSIS_IS_VERSIONED = False
LITE_BLOG_CONTENT_ANALYSIS_IS_SHARED = False
LITE_BLOG_CONTENT_ANALYSIS_IS_SYSTEM_ENTITY = False

LITE_BLOG_AI_VISIBILITY_TEST_DOCNAME = "lite_blog_ai_visibility_test_doc"
LITE_BLOG_AI_VISIBILITY_TEST_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
LITE_BLOG_AI_VISIBILITY_TEST_IS_VERSIONED = False
LITE_BLOG_AI_VISIBILITY_TEST_IS_SHARED = False
LITE_BLOG_AI_VISIBILITY_TEST_IS_SYSTEM_ENTITY = False

LITE_BLOG_DEEP_RESEARCH_REPORT_DOCNAME = "lite_blog_deep_research_report_doc"
LITE_BLOG_DEEP_RESEARCH_REPORT_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
LITE_BLOG_DEEP_RESEARCH_REPORT_IS_VERSIONED = False
LITE_BLOG_DEEP_RESEARCH_REPORT_IS_SHARED = False
LITE_BLOG_DEEP_RESEARCH_REPORT_IS_SYSTEM_ENTITY = False

LITE_BLOG_COMPANY_DOCNAME = "lite_blog_company_doc"
LITE_BLOG_COMPANY_NAMESPACE_TEMPLATE = "blog_company_profile_{item}"
LITE_BLOG_COMPANY_IS_VERSIONED = False
LITE_BLOG_COMPANY_IS_SHARED = False
LITE_BLOG_COMPANY_IS_SYSTEM_ENTITY = False

LITE_BLOG_CONTENT_DIAGNOSTIC_REPORT_DOCNAME = "lite_blog_content_diagnostic_report_doc"
LITE_BLOG_CONTENT_DIAGNOSTIC_REPORT_NAMESPACE_TEMPLATE = "blog_content_diagnostic_report_{item}"
LITE_BLOG_CONTENT_DIAGNOSTIC_REPORT_IS_VERSIONED = False
LITE_BLOG_CONTENT_DIAGNOSTIC_REPORT_IS_SHARED = False
LITE_BLOG_CONTENT_DIAGNOSTIC_REPORT_IS_SYSTEM_ENTITY = False

LITE_BLOG_COMPANY_AI_VISIBILITY_TEST_DOCNAME = "lite_blog_company_ai_baseline_doc"
LITE_BLOG_COMPANY_AI_VISIBILITY_TEST_NAMESPACE_TEMPLATE = "blog_analysis_{item}"
LITE_BLOG_COMPANY_AI_VISIBILITY_TEST_IS_VERSIONED = False
LITE_BLOG_COMPANY_AI_VISIBILITY_TEST_IS_SHARED = False
LITE_BLOG_COMPANY_AI_VISIBILITY_TEST_IS_SYSTEM_ENTITY = False

LITE_BLOG_AI_VISIBILITY_RAW_DATA_DOCNAME = "lite_blog_ai_visibility_raw_data_{_uuid_}"
LITE_BLOG_UPLOADED_FILES_DOCNAME = ""
LITE_BLOG_UPLOADED_FILES_NAMESPACE_TEMPLATE = "blog_uploaded_files_{item}"
LITE_BLOG_UPLOADED_FILES_IS_VERSIONED = False
LITE_BLOG_UPLOADED_FILES_IS_SHARED = False
LITE_BLOG_UPLOADED_FILES_IS_SYSTEM_ENTITY = False

# Blog Competitor Content Analysis - SPECIAL CASE: namespace gets lite_ prefix, docname stays same
LITE_BLOG_COMPETITOR_CONTENT_ANALYSIS_DOCNAME = "blog_competitor_content_analysis_{item}"  # NO lite_ prefix
LITE_BLOG_COMPETITOR_CONTENT_ANALYSIS_NAMESPACE_TEMPLATE = "lite_blog_competitor_content_analysis_namespace_{item}"  # WITH lite_ prefix
LITE_BLOG_COMPETITOR_CONTENT_ANALYSIS_IS_VERSIONED = False
LITE_BLOG_COMPETITOR_CONTENT_ANALYSIS_IS_SHARED = False
LITE_BLOG_COMPETITOR_CONTENT_ANALYSIS_IS_SYSTEM_ENTITY = False

